### ISSUE TITLE
Affine + Recurrent layer don't work together with STEPS>1 and BATCH_SIZE>1

### ISSUE THREAD

**Issue by buriy** [NervanaSystems/neon#122]
```python
from neon.backends import gen_backend
from neon.initializers import Uniform
from neon.layers import GeneralizedCost, Affine, Recurrent
from neon.models import Model
from neon.optimizers import RMSProp
from neon.transforms import Tanh, CrossEntropyMulti
from neon.callbacks.callbacks import Callbacks
from neon.util.argparser import NeonArgparser
from neon.transforms.activation import Rectlin, Softmax
from neon.data.dataiterator import DataIterator
from neon.layers.recurrent import RecurrentLast
import numpy


parser = NeonArgparser(__doc__)
args = parser.parse_args()

CLIP_GRADIENTS = True
NUM_EPOCHS = args.epochs
BATCH_SIZE = 4
LEN = 20
WIDTH = 170
STEPS = 20
X = numpy.zeros((LEN, WIDTH*STEPS))
Y = numpy.zeros((LEN, 1))

be = gen_backend(backend=args.backend,
                 batch_size=BATCH_SIZE,
                 rng_seed=args.rng_seed,
                 device_id=args.device_id,
                 default_dtype=args.datatype)

train_set = DataIterator(X, Y, 10, (WIDTH, STEPS), True)
valid_set = DataIterator(X, Y, 10, (WIDTH, STEPS), True)

init = Uniform(low=-0.08, high=0.08)

layers = [
    Affine(230, init, bias=init, activation=Rectlin()), # comment out this layer and it will work again
    Recurrent(140, init, activation=Tanh()), # attempts to run C(230, 80) += A(230, 170) * B(3400, 4)
    RecurrentLast(),
    Affine(10, init, bias=init, activation=Softmax()),
]

cost = GeneralizedCost(costfunc=CrossEntropyMulti(usebits=True))

model = Model(layers=layers)

optimizer = RMSProp(clip_gradients=CLIP_GRADIENTS, stochastic_round=args.rounding)

callbacks = Callbacks(model, train_set, output_file=args.output_file,
                      valid_set=valid_set, valid_freq=args.validation_freq,
                      progress_bar=args.progress_bar)

model.fit(train_set,
          optimizer=optimizer,
          num_epochs=NUM_EPOCHS,
          cost=cost,
          callbacks=callbacks)
```
```
Network Layers:
	Linear Layer 'LinearLayer': 170 inputs, 230 outputs
	Bias Layer 'BiasLayer': size 230
	Activation Layer 'ActivationLayer': Rectlin
	Recurrent RecurrentLayer
	RecurrentOutput choice RecurrentLastLayer : (140, 20) inputs, 140 outputs
	Linear Layer 'LinearLayer': 140 inputs, 10 outputs
	Bias Layer 'BiasLayer': size 10
	Activation Layer 'ActivationLayer': Softmax

Traceback (most recent call last):
  File "mytest.py", line 59, in <module>
    callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/models/model.py", line 149, in fit
    self._epoch_fit(dataset, callbacks)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/models/model.py", line 171, in _epoch_fit
    x = self.fprop(x)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/models/model.py", line 202, in fprop
    x = l.fprop(x, inference)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/layers/layer.py", line 503, in fprop
    self.be.compound_dot(A=self.W, B=self.inputs, C=self.outputs, bsum=self.batch_sum)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/backends/nervanagpu.py", line 1091, in compound_dot
    assert n == C.shape[1]
AssertionError
```

**Comment by apark263** [comment]
Affine layers implicitly de-sequencify sequential input.

In order to pass activations to a layer that demands sequential input
(recurrent/lstm/gru), you have to re-introduce the sequential attribute of
the activations coming out of the affine layer.

However, since affine layer is fully connected, there is no longer a causal
relationship between the inputs.

If you're ok with that, it would be easy enough to define a pass through
layer that just changes the in_shape to a recurrent tuple.

(just make a layer that passes the inputs straight through, but the config
step has flat in_shape and sequential out_shape)

**Comment by buriy** [comment]
Thanks a lot!
ReshapeLayer is what I thought about (similar to http://caffe.berkeleyvision.org/doxygen/classcaffe_1_1ReshapeLayer.html)
I also realized that all RNN examples don't have this Affine+RNN combination.
I'd like if you could add an example like this, and possibly include that kind of layer -- I believe a lot of people would be interested in learning how to do that transformation.
From documentation it's not currently possible to get how to solve this task in the best way -- only by experimentation & learning library design.
I'll try to make a pull request with my implementation.

**Comment by buriy** [comment]
Found the patch is much easier than what I thought initially:
```python
diff --git a/neon/layers/layer.py b/neon/layers/layer.py
index df2976e..589ea95 100644
--- a/neon/layers/layer.py
+++ b/neon/layers/layer.py
@@ -618,13 +618,14 @@ class Linear(ParameterLayer):
 
     def fprop(self, inputs, inference=False):
         self.inputs = inputs
-        self.be.compound_dot(A=self.W, B=self.inputs, C=self.outputs, bsum=self.batch_sum)
+        self.dev_inputs = inputs.reshape((self.nin, -1))
+        self.be.compound_dot(A=self.W, B=self.dev_inputs, C=self.outputs, bsum=self.batch_sum)
         return self.outputs
 
     def bprop(self, error, alpha=1.0, beta=0.0):
         if self.deltas:
             self.be.compound_dot(A=self.W.T, B=error, C=self.deltas, alpha=alpha, beta=beta)
-        self.be.compound_dot(A=error, B=self.inputs.T, C=self.dW)
+        self.be.compound_dot(A=error, B=self.dev_inputs.T, C=self.dW)
         return self.deltas
```
All tests pass.

**Comment by buriy** [comment]
@apark263 could you take a look at the proposed patch? Should I make a pull request?

**Comment by buriy** [comment]
Hmm. Actually can't confirm whether it's learning correctly after this patch. Looks like it is not.

**Comment by scttl** [comment]
Hi,

Thanks for your pull request.  Unfortunately we won't be able to accept it as it stands as we really don't want to introduce an extra reshape into the existing `Linear` layer across the board.  Until we actually add and document a proper Reshape layer your best bet is just to define your own custom layer and use that instead.

**Comment by buriy** [comment]
Btw my reshape layer looks like this:
```
class Reshape(Layer):

    """
    Arguments:
        init (Initializer, optional): Initializer object to use for
            initializing layer weights
    """

    def __init__(self, name="Reshape"):
        super(Reshape, self).__init__(name, "Disabled")
        self.has_params = False
        self.inputs = None

    def __str__(self):
        return "Reshape Layer '%s': %s inputs, %s outputs, %s steps" % (
               self.name, self.nin, self.nin, self.nsteps)

    def configure(self, in_obj):
        super(Reshape, self).configure(in_obj)
        (self.nin, self.nsteps) = self.in_shape
        self.out_shape = (self.nin, self.nsteps)
        return self

    def fprop(self, inputs, inference=False, beta=0.0):
        self.inputs = inputs
        tmp = inputs.reshape((self.nin, self.nsteps, self.be.bsz))
        self.outputs = tmp.reshape((self.nin, self.nsteps * self.be.bsz))
        return self.outputs

    def bprop(self, error, alpha=1.0, beta=0.0):
        return error
```
Might be also useful for #221 .
