### ISSUE TITLE
Version 1.1: __init__() got an unexpected keyword argument 'valid_set'

### ISSUE THREAD

**Issue by Jokeren** [NervanaSystems/neon#126]
neon examples/mnist_mlp.yaml 

        Traceback (most recent call last):
          File "/home/zkr/develop/neon/.venv/bin/neon", line 6, in <module>
            exec(compile(open(__file__).read(), __file__, 'exec'))
          File "/home/zkr/develop/neon/bin/neon", line 163, in <module>
            callbacks = Callbacks(model, train, args, valid_set=test)
        TypeError: __init__() got an unexpected keyword argument 'valid_set'

However, `python examples/mnist_mlp.py` works.

**Comment by scttl** [comment]
Fixed via #127
