### ISSUE TITLE
'Multicost' object has no attribute 'outputs'

### ISSUE THREAD

**Issue by suixudongi8** [NervanaSystems/neon#131]
When I run the example:mnist_branch.py with -eval 2 cmd arg, it will report:
Traceback (most recent call last):
  File "./mnist_branch.py", line 132, in <module>
    mlp.fit(train_set, optimizer=optimizer, num_epochs=num_epochs, cost=cost, callbacks=callbacks)
  File "/home/x/neon/neon/models/model.py", line 120, in fit
    callbacks.on_epoch_end(self.epoch_index)
  File "/home/x/neon/neon/callbacks/callbacks.py", line 203, in on_epoch_end
    c.on_epoch_end(epoch)
  File "/home/x/neon/neon/callbacks/callbacks.py", line 471, in on_epoch_end
    costbuf = self.model.cost.outputs[:, :bsz*nsteps]
AttributeError: 'Multicost' object has no attribute 'outputs'

**Comment by apark263** [comment]
Pending fix will be pushed soon

**Comment by suixudongi8** [comment]
Thanks for your hard work;)
