### ISSUE TITLE
Input shape not compatible?

### ISSUE THREAD

**Issue by willtwr** [NervanaSystems/neon#156]
Hi, 

I am trying to run CNN on a new dataset.
However, I am getting this error:

Traceback (most recent call last):
  File "/home/testing/PycharmProjects/ConvNet/neons/allcnnlarge.py", line 65, in <module>
    model.fit(train, optimizer=opt, num_epochs=250, cost=cost, callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/neon/models/model.py", line 119, in fit
    self._epoch_fit(dataset, callbacks)
  File "/usr/local/lib/python2.7/dist-packages/neon/models/model.py", line 142, in _epoch_fit
    self.total_cost[:] = self.total_cost + self.cost.get_cost(x, t)
  File "/usr/local/lib/python2.7/dist-packages/neon/layers/layer.py", line 1073, in get_cost
    self.outputs[:] = self.costfunc(inputs, targets)
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/nervanagpu.py", line 176, in __setitem__
    self.__getitem__(index)._assign(value)
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/nervanagpu.py", line 359, in _assign
    OpTreeNode.build("assign", self, value)
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/backend.py", line 1785, in build
    return node.execute()
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/backend.py", line 1806, in execute
    return backend.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/nervanagpu.py", line 978, in execute
    return call_compound_kernel(self._get_rand_state(), *stack)
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/float_ew.py", line 808, in call_compound_kernel
    "Input shape:%s not compatible" % (shape,))
TypeError: Input shape:[25, 64] not compatible

I am able to run the same settings (except number of classes) on Imagenet without any problem.
I tried to debug but it is just impossible for me to trace and understand what happened.

I am guessing the '64' in [25, 64] is the number of images in the minibatch.
The '25' seems like the number of classes because that is how the dataset categorized.
As usual, I set the nclass to 32 (I am using float16). 
I believe that this settings have no problem.

Can you kindly explain me what this part of code is checking?

Thank you.
William

**Comment by willtwr** [comment]
Hi,
I tried to remove one class so that I could use nclass=24, which is a number supported by neon and it works.
It seems that ImgMaster only support number of classes that are factor of 8 (when using float16)?

**Comment by scttl** [comment]
Hi William,

Looking at your traceback it looks like that part of the code is attempting to compute the updated cost (i.e. error) by comparing a single mini-batch worth of model outputs against its expected target values.  

To make neon performant, one of the (many) things we do is collect together the sequence of required arithmetic operations into an OpTree so that they can be compounded and lazily evaluated at a later point, when they are actually needed.  In your case, this evaluation uncovered a shape mismatch between the operands while trying to perform an elementwise operation.

Admittedly, this lazy evaluation can make things more confusing and difficult to debug, and the error message itself is pretty uninformative.  As you've already discovered, the bottom line is that you need to make sure your number of output classes is a multiple of 4 when using the GPU backend on convolutional networks.  This is mentioned briefly here: http://neon.nervanasys.com/docs/latest/design.html
