### ISSUE TITLE
illegal memory access when using DeconvCallback

### ISSUE THREAD

**Issue by yelite** [NervanaSystems/neon#163]
```
Visualization  [Find Max Act Imgs |████████████████████|    1/1    batches, 0.36s]
Visualization  [Compute Guided Bprop |████                |    6/26   layers, 0.00s]
Traceback (most recent call last):
  File "/home/liteye/projects/whale/locator/validation.py", line 110, in <module>
    callbacks=callbacks)
  File "/home/liteye/.local/lib/python2.7/site-packages/neon/models/model.py", line 126, in fit
    callbacks.on_train_end()
  File "/home/liteye/.local/lib/python2.7/site-packages/neon/callbacks/callbacks.py", line 190, in on_train_end
    c.on_train_end()
  File "/home/liteye/.local/lib/python2.7/site-packages/neon/callbacks/callbacks.py", line 846, in on_train_end
    self.visualize_layer(num_fm, act_size, layer_ind)
  File "/home/liteye/.local/lib/python2.7/site-packages/neon/callbacks/callbacks.py", line 959, in visualize_layer
    activation = be.array(activation)
  File "/home/liteye/.local/lib/python2.7/site-packages/neon/backends/nervanagpu.py", line 1016, in array
    rounding=self.round_mode).set(ary)
  File "/home/liteye/.local/lib/python2.7/site-packages/neon/backends/nervanagpu.py", line 390, in set
    drv.memcpy_htod_async(self.gpudata, ary, stream)
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: an illegal memory access was encountered
CUDA error 700 at: device.hpp:131
CUDA error 700 at: device.hpp:131
CUDA error 700 at: device.hpp:131
CUDA error 700 at: device.hpp:131
CUDA error 700 at: device.hpp:131
CUDA error 700 at: device.hpp:131
CUDA error 700 at: device.hpp:131
CUDA error 700 at: device.hpp:131
CUDA error 700 at: device.hpp:131
CUDA error 700 at: device.hp:131
```

In `GPUTensor.set`, 
- `self` is `GPUTensor(base 0x759b20000) name:None shape:(16384, 32) dtype:float32 strides:(32, 1) is_trans:False is_contiguous:True`
- `ary` is ndarray with shape (16384, 32) and dtype float32

```
>>> neon.__version__
Out[6]: '1.1.4+e09fc11'
>>> pycuda.VERSION
Out[4]: (2015, 1, 3)
```

Any idea on this issue?

**Comment by wconstab** [comment]
Which model were you running? It would be helpful to have the exact command line, and any other info needed to reproduce the issue locally.

**Comment by nervetumer** [comment]
Also can you provide more information on ary.  For example, ary.flags and ary.strides

**Comment by yelite** [comment]
ary.flags
```
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

ary.strides = (128, 4)

I'm still working on a minimal script for reproducing this.

**Comment by wconstab** [comment]
Were you able to come up with a script to reproduce the issue? Are you still seeing the issue?

**Comment by yelite** [comment]
During the winter break I am away from my GPU... It will be a few weeks before I can touch it again.

**Comment by scttl** [comment]
Going to close this for the time being. @yelite please re-open once you have a script that we can take a further look at.
