### ISSUE TITLE
cannot run "neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp32.yaml"

### ISSUE THREAD

**Issue by andyyuan78** [NervanaSystems/neon#21]
ubgpu@ubgpu:~/github/neon$ neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp32.yaml
WARNING:neon.util.persist:deserializing object from:  examples/convnet/i1k-alexnet-fp32.yaml
WARNING:neon.datasets.imageset:Imageset initialized with dtype <type 'numpy.float32'>
2015-05-11 01:13:02,940 WARNING:neon - setting log level to: 20
2015-05-11 01:13:02,945 WARNING:__init__ - nervanagpu not found, can't run via GPU
Traceback (most recent call last):
  File "/usr/local/bin/neon", line 199, in <module>
    experiment, result, status = main()
  File "/usr/local/bin/neon", line 162, in main
    device_id=args.device_id)
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/__init__.py", line 157, in gen_backend
    raise RuntimeError("Can't find CUDA capable GPU")
RuntimeError: Can't find CUDA capable GPU
ubgpu@ubgpu:~/github/neon$ which nvcc
/usr/local/cuda/bin/nvcc
ubgpu@ubgpu:~/github/neon$ 

my GPU is GTX970!!!

**Comment by andyyuan78** [comment]
ubgpu@ubgpu:~/github/neon$ neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp16.yaml
WARNING:neon.util.persist:deserializing object from:  examples/convnet/i1k-alexnet-fp16.yaml
WARNING:neon.datasets.imageset:Imageset initialized with dtype <type 'numpy.float16'>
2015-05-11 01:19:23,544 WARNING:neon - setting log level to: 20
2015-05-11 01:19:23,548 WARNING:__init__ - nervanagpu not found, can't run via GPU
Traceback (most recent call last):
  File "/usr/local/bin/neon", line 199, in <module>
    experiment, result, status = main()
  File "/usr/local/bin/neon", line 162, in main
    device_id=args.device_id)
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/__init__.py", line 157, in gen_backend
    raise RuntimeError("Can't find CUDA capable GPU")
RuntimeError: Can't find CUDA capable GPU
ubgpu@ubgpu:~/github/neon$

**Comment by Kaixhin** [comment]
2015-05-11 01:19:23,548 WARNING:init - nervanagpu not found, can't run via GPU

Have you installed [nervanagpu](https://github.com/NervanaSystems/nervanagpu) and made sure all the tests passed? Details are in the README of the repository.

The full list of dependencies for GPU usage are in the [docs](http://neon.nervanasys.com/docs/latest/installation.html) for neon.

**Comment by scttl** [comment]
Because it looks like you were using virtualenv in the other issue you opened (#18) I suspect you maybe forgot to activate it for the runs above.  Try the following (from your neon directory):
```
. .venv/bin/activate
neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp16.yaml
```

If that still fails then you need to first install nervanagpu as @Kaixhin mentions.

**Comment by andyyuan78** [comment]
it solved!
