### ISSUE TITLE
Support model serialization and saving predictions for RNN's and LSTM's

### ISSUE THREAD

**Issue by scttl** [NervanaSystems/neon#23]
Attempts to save predictions (`predictions: ['train', 'test']`) or model parameters (`serialized_path: "my_model.prm"`) on either the RNN or LSTM example networks result in a ValueError being raised instead of successful saving:
```
Traceback (most recent call last):
  File "bin/neon", line 240, in <module>
    experiment, result, status = main()
  File "bin/neon", line 208, in main
    result = experiment.run()
  File "/home/users/scott/repo/neon/neon/experiments/fit_predict_err.py", line 114, in run
    pred_set)
  File "/home/users/scott/repo/neon/neon/models/mlp.py", line 241, in predict_fullset
    reference[:, start:end] = self.cost_layer.get_reference()
  File "/home/users/scott/repo/neon/neon/backends/cpu.py", line 157, in __setitem__
    self._tensor[clean_key] = np.reshape(self._clean(value), req_shape)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 217, in reshape
    return _wrapit(a, 'reshape', newshape, order=order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: total size of new array must be unchanged
```

**Comment by lglhuada** [comment]
Has it been solved or not? I am going to train a LSTM-based model.

**Comment by scttl** [comment]
@lglhuada I just pushed a commit that should address this.
