### ISSUE TITLE
TypeError: fprop() got an unexpected keyword argument 'beta'

### ISSUE THREAD

**Issue by thouis** [NervanaSystems/neon#232]
The code pasted below dies with this traceback:
(I have other bugs related to this network structure, which I'll file separately).

I'm at 1.3.0+344372b.

====
trace
====
```
Traceback (most recent call last):
  File "bsum_bug.py", line 65, in <module>
    model.fit(train, optimizer=opt_gdm, num_epochs=num_epochs, cost=cost, callbacks=Callbacks(model))
  File "/net/seasfs02/srv/export/pfister_lab/share_root/thouis/neon/neon/models/model.py", line 149, in fit
    self._epoch_fit(dataset, callbacks)
  File "/net/seasfs02/srv/export/pfister_lab/share_root/thouis/neon/neon/models/model.py", line 171, in _epoch_fit
    x = self.fprop(x)
  File "/net/seasfs02/srv/export/pfister_lab/share_root/thouis/neon/neon/models/model.py", line 202, in fprop
    return self.layers.fprop(x, inference)
  File "/net/seasfs02/srv/export/pfister_lab/share_root/thouis/neon/neon/layers/container.py", line 192, in fprop
    x = l.fprop(x, inference)
  File "/net/seasfs02/srv/export/pfister_lab/share_root/thouis/neon/neon/layers/container.py", line 396, in fprop
    l.fprop(inputs, inference, beta=beta)
  File "/net/seasfs02/srv/export/pfister_lab/share_root/thouis/neon/neon/layers/container.py", line 190, in fprop
    x = l.fprop(x, inference, beta=beta)
TypeError: fprop() got an unexpected keyword argument 'beta'
>>> import pdb
p>>> pdb.pm()
> /net/seasfs02/srv/export/pfister_lab/share_root/thouis/neon/neon/layers/container.py(190)fprop()
-> x = l.fprop(x, inference, beta=beta)
(Pdb) p l
<neon.layers.layer.Bias object at 0x2b276ddf9590>
(Pdb) 
```

====
code
====

```
import numpy as np

from neon.initializers import GlorotUniform, Constant, Uniform
from neon.layers import Conv, GeneralizedCost, Dropout, SkipNode, Activation, Bias, Affine, MergeSum
from neon.models import Model
from neon.optimizers import GradientDescentMomentum
from neon.transforms import Rectlin, CrossEntropyBinary, Softmax
from neon.callbacks.callbacks import Callbacks
from neon.util.argparser import NeonArgparser
from neon.data import ArrayIterator

# parse the command line arguments
parser = NeonArgparser(__doc__)
args = parser.parse_args()

# hyperparameters
num_epochs = args.epochs
network_depth = 16
num_features = 128

def conv_params(fsize, relu=True, batch_norm=True):
    padding = {'pad_h': fsize[0] // 2, 'pad_w': fsize[1] // 2}  # always pad to preserve width and height
    return dict(fshape=fsize,
                activation=(Rectlin() if relu else None),
                padding=padding,
                batch_norm=batch_norm,
                init=GlorotUniform())

def resnet_module(nfm):
    sidepath = SkipNode()
    mainpath = [Conv(**conv_params((3, 3, nfm))),
                Bias(Constant()),
                Dropout(0.9),
                Conv(**conv_params((3, 3, nfm), relu=False)),
                Bias(Constant())]
    return [MergeSum([sidepath, mainpath]),
            Activation(Rectlin())]

def build_model(depth, nfm):
    # input - expand to #nfm feature maps
    layers = [Conv(**conv_params((5, 5, nfm))),
              Dropout(0.8)]

    for d in range(depth):
        layers += resnet_module(nfm)

    # final output: 1 channel
    layers += [Dropout(0.5),
               Affine(362, init=Uniform(-1.0 / (362 * nfm), 1.0 / (362 * nfm)), activation=Softmax())]

    return Model(layers=layers)

X = X = np.random.rand(10000, 48 * 19 * 19)  # X.shape = (10000, 48*19*19)
y = np.random.randint(0, 362, 10000)  # y.shape = (10000, )
train = ArrayIterator(X=X, y=y, nclass=362, lshape=(48, 19, 19))

cost = GeneralizedCost(costfunc=CrossEntropyBinary())
opt_gdm = GradientDescentMomentum(learning_rate=0.01,
                                  momentum_coef=0.9,
                                  stochastic_round=args.rounding)

model = build_model(network_depth, num_features)
model.fit(train, optimizer=opt_gdm, num_epochs=num_epochs, cost=cost, callbacks=Callbacks(model))
```

**Comment by apark263** [comment]
good find -- some layers are indeed missing support beta for accumulation
at the moment...  could you try switching the order of sidepath and
mainpath in your MergeSum layer?  that may be a quick, albeit deeply
unsatisfying fix for now.

**Comment by thouis** [comment]
Hitting #233 when I do that.

**Comment by thouis** [comment]
I hit this again, today, trying to implement a Swapout network (https://arxiv.org/pdf/1605.06465v1.pdf), where both paths from the residual network terminate in a Dropout().

Is there a simple fix for this?  It seems like just adding "beta * self.outputs + ..." to the output computation of Dropout is the right answer, but would like some verification.

**Comment by apark263** [comment]
dropout, bias, and activation layers are a little bit more complicated because they don't own their own output buffers, so just accumulating as `self.outputs[:] = self.outputs * beta + ...` would yield the incorrect result.

We could make versions of these layers that do own their output buffers, but there would be a corresponding increase in memory usage, which could be significant for these deep networks.  In the meantime, the more recent resnet architectures do exhibit swap out-like behavior by allowing more direct paths through the network, and we have implemented that in our later cifar msra example.
