### ISSUE TITLE
set up error on TitanX

### ISSUE THREAD

**Issue by gujunli** [NervanaSystems/neon#236]
xamples/mnist_mlp.py
Traceback (most recent call last):
  File "examples/mnist_mlp.py", line 55, in <module>
    args = parser.parse_args()
  File "/home/junli/.local/lib/python2.7/site-packages/neon/util/argparser.py", line 327, in parse_args
    compat_mode=args.compat_mode)
  File "/home/junli/.local/lib/python2.7/site-packages/neon/backends/__init__.py", line 108, in gen_backend
    cache_dir=cache_dir)
  File "/home/junli/.local/lib/python2.7/site-packages/neon/backends/nervanagpu.py", line 695, in __init__
    deterministic=deterministic)
  File "/home/junli/.local/lib/python2.7/site-packages/neon/backends/backend.py", line 440, in __init__
    self.rng = self.gen_rng(rng_seed)
  File "/home/junli/.local/lib/python2.7/site-packages/neon/backends/nervanagpu.py", line 806, in gen_rng
    self.pcg = rng_mrg()
  File "/home/junli/.local/lib/python2.7/site-packages/pycuda/curandom.py", line 788, in __init__
    mrg32k3a_skip_ahead_sequence_source+random_skip_ahead64_source)
  File "/home/junli/.local/lib/python2.7/site-packages/pycuda/curandom.py", line 605, in __init__
    state_type, vector_type, generator_bits, additional_source)
  File "/home/junli/.local/lib/python2.7/site-packages/pycuda/curandom.py", line 440, in __init__
    self.module = module = pycuda.compiler.SourceModule(source, no_extern_c=True)
  File "/home/junli/.local/lib/python2.7/site-packages/pycuda/compiler.py", line 265, in __init__
    arch, code, cache_dir, include_dirs)
  File "/home/junli/.local/lib/python2.7/site-packages/pycuda/compiler.py", line 255, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/home/junli/.local/lib/python2.7/site-packages/pycuda/compiler.py", line 78, in compile_plain
    checksum.update(preprocess_source(source, options, nvcc).encode("utf-8"))
  File "/home/junli/.local/lib/python2.7/site-packages/pycuda/compiler.py", line 50, in preprocess_source
    result, stdout, stderr = call_capture_output(cmdline, error_on_nonzero=False)
  File "/home/junli/.local/lib/python2.7/site-packages/pytools/prefork.py", line 197, in call_capture_output
    return forker[0].call_capture_output(cmdline, cwd, error_on_nonzero)
  File "/home/junli/.local/lib/python2.7/site-packages/pytools/prefork.py", line 54, in call_capture_output
    % ( " ".join(cmdline), e))
pytools.prefork.ExecError: error invoking 'nvcc --preprocess -arch sm_52 -I/home/junli/.local/lib/python2.7/site-packages/pycuda/cuda /tmp/tmpS2fZmZ.cu --compiler-options -P': [Errno 2] No such file or directory

**Comment by gujunli** [comment]
"which nvcc" returns nothing
I am installing pycuda now, if that is the issue

**Comment by hanlin-nervana** [comment]
If `which nvcc` returns empty, you may need to add cuda to your path. Depending on your cuda install location, something like this:

```
export PATH="/usr/local/cuda/bin:"$PATH
export LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/cuda/lib:/usr/local/lib:"$LD_LIBRARY_PATH
```

**Comment by gujunli** [comment]
right. I added it in the .bashrc file. But i forgot to source it.
After sourcing it, it seems to make progress now

**Comment by gujunli** [comment]
map.py example ran successfully. you can close this thread now. Thank you!
