### ISSUE TITLE
assertion fails on fresh checkout

### ISSUE THREAD

**Issue by nitbix** [NervanaSystems/neon#259]
I *suspect* there's something wrong in the ZCA whitening. I tried running examples/cifar10_allcnn.py from a fresh checkout (commit bc196cbe4131a76cd0c584e93aa7f8285b6243cb) and got the following:

```
$ python cifar10_allcnn.py
Downloading file: /home/nitbix/nervana/data/cifar-10-python.tar.gz
Download Progress |██████████████████████████████████████████████████| Download Complete
Traceback (most recent call last):
  File "cifar10_allcnn.py", line 48, in <module>
    whiten=True)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.4.0-py2.7.egg/neon/data/dataloaders.py", line 84, in load_cifar10
    return cfiar10_dataset.load_data()
  File "/usr/local/lib/python2.7/dist-packages/neon-1.4.0-py2.7.egg/neon/data/image.py", line 160, in load_data
    X_train, X_test = self.zca_whiten(X_train, X_test, cache=zca_cache)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.4.0-py2.7.egg/neon/data/image.py", line 215, in zca_whiten
    meanX, W = CIFAR10._compute_zca_transform(train)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.4.0-py2.7.egg/neon/data/image.py", line 198, in _compute_zca_transform
    assert D.min() > 0
AssertionError

```

**Comment by hanlin-nervana** [comment]
Hello,

We are having some trouble reproducing your issue. Can you try building a fresh copy of neon and point it at a different data directory with the `-w` flag to force a fresh download of the dataset? Thanks!
