### ISSUE TITLE
Neon installation failed on RHEL 6 with Anaconda! Is it a numpy issue??

### ISSUE THREAD

**Issue by swapnilsj** [NervanaSystems/neon#289]
I tried installing Neon on RHEL 6 using Anaconda3-4.1.1 but failed with below issue:
Is it a problem with numpy 1.9.2 version specified in requirements.txt?

```
Installing neon dependencies system wide...
Requirement already satisfied (use --upgrade to upgrade): cython==0.23.1 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): configargparse==0.9.3 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): numpy==1.9.2 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): pyyaml==3.11 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pep8==1.7.0 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): flake8==2.4.1 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pytest==2.7.3 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): pytest-cov==2.0.0 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): posix_ipc==1.0.0 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): pillow==2.9.0 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): pylint==1.5.5 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): sphinx==1.3.1 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from -r requirements.txt (line 11))
Collecting h5py==2.5.0 (from -r requirements.txt (line 12))
  Using cached h5py-2.5.0.tar.gz
Collecting appdirs==1.4.0 (from -r requirements.txt (line 13))
  Using cached appdirs-1.4.0-py2.py3-none-any.whl
Collecting future==0.15.2 (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): mccabe<0.4,>=0.2.1 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from flake8==2.4.1->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pyflakes<0.9,>=0.8.1 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from flake8==2.4.1->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.29 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from pytest==2.7.3->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): coverage>=3.7.1 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from pytest-cov==2.0.0->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): astroid<1.5.0,>=1.4.5 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from pylint==1.5.5->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): colorama in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from pylint==1.5.5->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): six in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from pylint==1.5.5->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): docutils>=0.11 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from sphinx==1.3.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.3 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from sphinx==1.3.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): alabaster<0.8,>=0.7 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from sphinx==1.3.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): snowballstemmer>=1.1 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from sphinx==1.3.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): babel>=1.3 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from sphinx==1.3.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): Pygments>=2.0 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from sphinx==1.3.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): sphinx-rtd-theme<0.2,>=0.1 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from sphinx==1.3.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): Cython>=0.17 in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from h5py==2.5.0->-r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): wrapt in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from astroid<1.5.0,>=1.4.5->pylint==1.5.5->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): lazy-object-proxy in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from astroid<1.5.0,>=1.4.5->pylint==1.5.5->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from Jinja2>=2.3->sphinx==1.3.1->-r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in /<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages (from babel>=1.3->sphinx==1.3.1->-r requirements.txt (line 11))
Building wheels for collected packages: h5py
  Running setup.py bdist_wheel for h5py: started
  Running setup.py bdist_wheel for h5py: finished with status 'error'
  Complete output from command /<user_path>/anaconda3/envs/neon/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9ap_xw3l/h5py/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpdstugcytpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/h5py
  copying h5py/highlevel.py -> build/lib.linux-x86_64-3.5/h5py
  copying h5py/ipy_completer.py -> build/lib.linux-x86_64-3.5/h5py
  copying h5py/__init__.py -> build/lib.linux-x86_64-3.5/h5py
  copying h5py/version.py -> build/lib.linux-x86_64-3.5/h5py
  creating build/lib.linux-x86_64-3.5/h5py/_hl
  copying h5py/_hl/selections2.py -> build/lib.linux-x86_64-3.5/h5py/_hl
  copying h5py/_hl/group.py -> build/lib.linux-x86_64-3.5/h5py/_hl
  copying h5py/_hl/attrs.py -> build/lib.linux-x86_64-3.5/h5py/_hl
  copying h5py/_hl/datatype.py -> build/lib.linux-x86_64-3.5/h5py/_hl
  copying h5py/_hl/dataset.py -> build/lib.linux-x86_64-3.5/h5py/_hl
  copying h5py/_hl/dims.py -> build/lib.linux-x86_64-3.5/h5py/_hl
  copying h5py/_hl/filters.py -> build/lib.linux-x86_64-3.5/h5py/_hl
  copying h5py/_hl/files.py -> build/lib.linux-x86_64-3.5/h5py/_hl
  copying h5py/_hl/selections.py -> build/lib.linux-x86_64-3.5/h5py/_hl
  copying h5py/_hl/base.py -> build/lib.linux-x86_64-3.5/h5py/_hl
  copying h5py/_hl/__init__.py -> build/lib.linux-x86_64-3.5/h5py/_hl
  creating build/lib.linux-x86_64-3.5/h5py/tests
  copying h5py/tests/common.py -> build/lib.linux-x86_64-3.5/h5py/tests
  copying h5py/tests/__init__.py -> build/lib.linux-x86_64-3.5/h5py/tests
  creating build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_group.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_h5f.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/common.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_objects.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_h5t.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_selections.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_dimension_scales.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_h5p.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_attrs_data.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_datatype.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/__init__.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_attrs.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_dataset.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_slicing.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_file.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_h5.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  copying h5py/tests/old/test_base.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
  creating build/lib.linux-x86_64-3.5/h5py/tests/hl
  copying h5py/tests/hl/test_dataset_getitem.py -> build/lib.linux-x86_64-3.5/h5py/tests/hl
  copying h5py/tests/hl/test_attribute_create.py -> build/lib.linux-x86_64-3.5/h5py/tests/hl
  copying h5py/tests/hl/__init__.py -> build/lib.linux-x86_64-3.5/h5py/tests/hl
  copying h5py/tests/hl/test_dataset_swmr.py -> build/lib.linux-x86_64-3.5/h5py/tests/hl
  copying h5py/tests/hl/test_file.py -> build/lib.linux-x86_64-3.5/h5py/tests/hl
  copying h5py/tests/hl/test_dims_dimensionproxy.py -> build/lib.linux-x86_64-3.5/h5py/tests/hl
  running build_ext
  Autodetected HDF5 1.8.17
  ********************************************************************************
                         Summary of the h5py configuration
  
      Path to HDF5: None
      HDF5 Version: '1.8.17'
       MPI Enabled: False
  Rebuild Required: False
  
  ********************************************************************************
  Executing api_gen rebuild of defs
  Executing cythonize()
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-9ap_xw3l/h5py/setup.py", line 140, in <module>
      cmdclass = CMDCLASS,
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-9ap_xw3l/h5py/setup_build.py", line 172, in run
      self.extensions = cythonize(self._make_extensions(config),
    File "/tmp/pip-build-9ap_xw3l/h5py/setup_build.py", line 72, in _make_extensions
      import numpy
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/numpy/__init__.py", line 184, in <module>
      from . import add_newdocs
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
      from numpy.lib import add_newdoc
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
      from .type_check import *
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
      import numpy.core.numeric as _nx
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/numpy/core/__init__.py", line 25, in <module>
      from . import numeric
    File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/numpy/core/numeric.py", line 73, in <module>
      MAY_SHARE_BOUNDS = multiarray.MAY_SHARE_BOUNDS
  AttributeError: module 'numpy.core.multiarray' has no attribute 'MAY_SHARE_BOUNDS'
  
  ----------------------------------------
  Running setup.py clean for h5py
Failed to build h5py
Installing collected packages: h5py, appdirs, future
  Found existing installation: h5py 2.6.0
    Uninstalling h5py-2.6.0:
      Successfully uninstalled h5py-2.6.0
  Running setup.py install for h5py: started
    Running setup.py install for h5py: finished with status 'error'
    Complete output from command /<user_path>/anaconda3/envs/neon/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9ap_xw3l/h5py/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7uv73qdb-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/h5py
    copying h5py/highlevel.py -> build/lib.linux-x86_64-3.5/h5py
    copying h5py/ipy_completer.py -> build/lib.linux-x86_64-3.5/h5py
    copying h5py/__init__.py -> build/lib.linux-x86_64-3.5/h5py
    copying h5py/version.py -> build/lib.linux-x86_64-3.5/h5py
    creating build/lib.linux-x86_64-3.5/h5py/_hl
    copying h5py/_hl/selections2.py -> build/lib.linux-x86_64-3.5/h5py/_hl
    copying h5py/_hl/group.py -> build/lib.linux-x86_64-3.5/h5py/_hl
    copying h5py/_hl/attrs.py -> build/lib.linux-x86_64-3.5/h5py/_hl
    copying h5py/_hl/datatype.py -> build/lib.linux-x86_64-3.5/h5py/_hl
    copying h5py/_hl/dataset.py -> build/lib.linux-x86_64-3.5/h5py/_hl
    copying h5py/_hl/dims.py -> build/lib.linux-x86_64-3.5/h5py/_hl
    copying h5py/_hl/filters.py -> build/lib.linux-x86_64-3.5/h5py/_hl
    copying h5py/_hl/files.py -> build/lib.linux-x86_64-3.5/h5py/_hl
    copying h5py/_hl/selections.py -> build/lib.linux-x86_64-3.5/h5py/_hl
    copying h5py/_hl/base.py -> build/lib.linux-x86_64-3.5/h5py/_hl
    copying h5py/_hl/__init__.py -> build/lib.linux-x86_64-3.5/h5py/_hl
    creating build/lib.linux-x86_64-3.5/h5py/tests
    copying h5py/tests/common.py -> build/lib.linux-x86_64-3.5/h5py/tests
    copying h5py/tests/__init__.py -> build/lib.linux-x86_64-3.5/h5py/tests
    creating build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_group.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_h5f.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/common.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_objects.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_h5t.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_selections.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_dimension_scales.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_h5p.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_attrs_data.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_datatype.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/__init__.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_attrs.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_dataset.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_slicing.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_file.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_h5.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    copying h5py/tests/old/test_base.py -> build/lib.linux-x86_64-3.5/h5py/tests/old
    creating build/lib.linux-x86_64-3.5/h5py/tests/hl
    copying h5py/tests/hl/test_dataset_getitem.py -> build/lib.linux-x86_64-3.5/h5py/tests/hl
    copying h5py/tests/hl/test_attribute_create.py -> build/lib.linux-x86_64-3.5/h5py/tests/hl
    copying h5py/tests/hl/__init__.py -> build/lib.linux-x86_64-3.5/h5py/tests/hl
    copying h5py/tests/hl/test_dataset_swmr.py -> build/lib.linux-x86_64-3.5/h5py/tests/hl
    copying h5py/tests/hl/test_file.py -> build/lib.linux-x86_64-3.5/h5py/tests/hl
    copying h5py/tests/hl/test_dims_dimensionproxy.py -> build/lib.linux-x86_64-3.5/h5py/tests/hl
    running build_ext
    Autodetected HDF5 1.8.17
    ********************************************************************************
                           Summary of the h5py configuration
    
        Path to HDF5: None
        HDF5 Version: '1.8.17'
         MPI Enabled: False
    Rebuild Required: False
    
    ********************************************************************************
    Executing cythonize()
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9ap_xw3l/h5py/setup.py", line 140, in <module>
        cmdclass = CMDCLASS,
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/setuptools-25.1.6-py3.5.egg/setuptools/command/install.py", line 61, in run
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-9ap_xw3l/h5py/setup_build.py", line 172, in run
        self.extensions = cythonize(self._make_extensions(config),
      File "/tmp/pip-build-9ap_xw3l/h5py/setup_build.py", line 72, in _make_extensions
        import numpy
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/numpy/__init__.py", line 184, in <module>
        from . import add_newdocs
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
        from numpy.lib import add_newdoc
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
        from .type_check import *
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
        import numpy.core.numeric as _nx
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/numpy/core/__init__.py", line 25, in <module>
        from . import numeric
      File "/<user_path>/anaconda3/envs/neon/lib/python3.5/site-packages/numpy/core/numeric.py", line 73, in <module>
        MAY_SHARE_BOUNDS = multiarray.MAY_SHARE_BOUNDS
    AttributeError: module 'numpy.core.multiarray' has no attribute 'MAY_SHARE_BOUNDS'
    
    ----------------------------------------
  Rolling back uninstall of h5py
```

**Comment by buriy** [comment]
If I remember correctly, h5py v 2.5.0 can't install from a binary package and attempts to compile (but doesn't do well with numpy 1.9), v 2.6.0 can.
I just changed all "==" to ">=" in neon requirements.txt file.

**Comment by swapnilsj** [comment]
Thanks. It worked! Do you think these changes in requirements.txt be pushed since there is no information about the above changes for installation on RHEL??

**Comment by jennifermyers** [comment]
Thanks for the reports on this issue! In the next release, neon 1.6, we'll be bringing all requirements.txt up to date which should address this issue.
