### ISSUE TITLE
make sysinstall: fatal error: 'Python.h' file not found

### ISSUE THREAD

**Issue by marcj** [NervanaSystems/neon#290]
Mac OS 10.11.3 (15D21)

```
marc@osx ~ $ pyvenv myenv
marc@osx ~ $ source myenv/bin/activate
(myenv) marc@osx ~/bude/neon (master*) $ python --version
Python 3.5.2
(myenv) marc@osx ~ $ cd bude/
(myenv) marc@osx ~ $ git clone https://github.com/NervanaSystems/neon.git
(myenv) marc@osx ~ $ cd neon
(myenv) marc@osx ~/bude/neon (master*) $ make sysinstall
Installing neon dependencies system wide...
Collecting cython==0.23.1
  Using cached Cython-0.23.1.tar.gz
Installing collected packages: cython
  Running setup.py install for cython ... done
Successfully installed cython-0.23.1
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting configargparse==0.9.3 (from -r requirements.txt (line 1))
  Using cached ConfigArgParse-0.9.3.tar.gz
Collecting numpy==1.9.2 (from -r requirements.txt (line 2))
  Using cached numpy-1.9.2.zip
Collecting pyyaml==3.11 (from -r requirements.txt (line 3))
  Using cached PyYAML-3.11.zip
Collecting pep8==1.7.0 (from -r requirements.txt (line 4))
  Using cached pep8-1.7.0-py2.py3-none-any.whl
Collecting flake8==2.4.1 (from -r requirements.txt (line 5))
  Using cached flake8-2.4.1-py2.py3-none-any.whl
Collecting pytest==2.7.3 (from -r requirements.txt (line 6))
  Using cached pytest-2.7.3-py2.py3-none-any.whl
Collecting pytest-cov==2.0.0 (from -r requirements.txt (line 7))
  Using cached pytest_cov-2.0.0-py2.py3-none-any.whl
Collecting posix-ipc==1.0.0 (from -r requirements.txt (line 8))
  Using cached posix_ipc-1.0.0.tar.gz
Collecting pillow==2.9.0 (from -r requirements.txt (line 9))
  Using cached Pillow-2.9.0.zip
Collecting pylint==1.5.5 (from -r requirements.txt (line 10))
  Using cached pylint-1.5.5-py2.py3-none-any.whl
Collecting sphinx==1.3.1 (from -r requirements.txt (line 11))
  Using cached Sphinx-1.3.1-py2.py3-none-any.whl
Collecting h5py==2.5.0 (from -r requirements.txt (line 12))
  Using cached h5py-2.5.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting appdirs==1.4.0 (from -r requirements.txt (line 13))
  Using cached appdirs-1.4.0-py2.py3-none-any.whl
Collecting future==0.15.2 (from -r requirements.txt (line 14))
  Using cached future-0.15.2.tar.gz
Collecting pyflakes<0.9,>=0.8.1 (from flake8==2.4.1->-r requirements.txt (line 5))
  Using cached pyflakes-0.8.1-py2.py3-none-any.whl
Collecting mccabe<0.4,>=0.2.1 (from flake8==2.4.1->-r requirements.txt (line 5))
  Using cached mccabe-0.3.1-py2.py3-none-any.whl
Collecting py>=1.4.29 (from pytest==2.7.3->-r requirements.txt (line 6))
  Using cached py-1.4.31-py2.py3-none-any.whl
Collecting coverage>=3.7.1 (from pytest-cov==2.0.0->-r requirements.txt (line 7))
  Using cached coverage-4.2-cp35-cp35m-macosx_10_10_x86_64.whl
Collecting colorama (from pylint==1.5.5->-r requirements.txt (line 10))
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting six (from pylint==1.5.5->-r requirements.txt (line 10))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting astroid<1.5.0,>=1.4.5 (from pylint==1.5.5->-r requirements.txt (line 10))
  Using cached astroid-1.4.8-py2.py3-none-any.whl
Collecting Jinja2>=2.3 (from sphinx==1.3.1->-r requirements.txt (line 11))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting babel>=1.3 (from sphinx==1.3.1->-r requirements.txt (line 11))
  Using cached Babel-2.3.4-py2.py3-none-any.whl
Collecting docutils>=0.11 (from sphinx==1.3.1->-r requirements.txt (line 11))
  Using cached docutils-0.12-py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx==1.3.1->-r requirements.txt (line 11))
  Using cached snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting sphinx-rtd-theme<0.2,>=0.1 (from sphinx==1.3.1->-r requirements.txt (line 11))
  Using cached sphinx_rtd_theme-0.1.9-py3-none-any.whl
Collecting alabaster<0.8,>=0.7 (from sphinx==1.3.1->-r requirements.txt (line 11))
  Using cached alabaster-0.7.9-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx==1.3.1->-r requirements.txt (line 11))
  Using cached Pygments-2.1.3-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): Cython>=0.17 in /Users/marc/myenv/lib/python3.5/site-packages (from h5py==2.5.0->-r requirements.txt (line 12))
Collecting wrapt (from astroid<1.5.0,>=1.4.5->pylint==1.5.5->-r requirements.txt (line 10))
  Using cached wrapt-1.10.8.tar.gz
Collecting lazy-object-proxy (from astroid<1.5.0,>=1.4.5->pylint==1.5.5->-r requirements.txt (line 10))
  Using cached lazy-object-proxy-1.2.2.tar.gz
Collecting MarkupSafe (from Jinja2>=2.3->sphinx==1.3.1->-r requirements.txt (line 11))
  Using cached MarkupSafe-0.23.tar.gz
Collecting pytz>=0a (from babel>=1.3->sphinx==1.3.1->-r requirements.txt (line 11))
  Using cached pytz-2016.6.1-py2.py3-none-any.whl
Installing collected packages: configargparse, numpy, pyyaml, pep8, pyflakes, mccabe, flake8, py, pytest, coverage, pytest-cov, posix-ipc, pillow, colorama, six, wrapt, lazy-object-proxy, astroid, pylint, MarkupSafe, Jinja2, pytz, babel, docutils, snowballstemmer, sphinx-rtd-theme, alabaster, Pygments, sphinx, h5py, appdirs, future
  Running setup.py install for configargparse ... done
  Running setup.py install for numpy ... error
    Complete output from command /Users/marc/myenv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-ik09d_fe-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/marc/myenv/include/site/python3.5/numpy:
    Running from numpy source directory.
    non-existing path in 'numpy/distutils': 'site.cfg'
    non-existing path in 'numpy/f2py': 'docs'
    non-existing path in 'numpy/f2py': 'f2py.1'
    F2PY Version 2
    blas_opt_info:
    blas_mkl_info:
      libraries mkl,vml,guide not found in ['/Users/marc/myenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['/Users/marc/myenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['/Users/marc/myenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['/Users/marc/myenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['/Users/marc/myenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['/Users/marc/myenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE

      FOUND:
        extra_compile_args = ['-msse3', '-DAPPLE_ACCELERATE_SGEMV_PATCH', '-I/System/Library/Frameworks/vecLib.framework/Headers']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3)]

    non-existing path in 'numpy/lib': 'benchmarks'
    lapack_opt_info:
    openblas_lapack_info:
      libraries openblas not found in ['/Users/marc/myenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE

    lapack_mkl_info:
    mkl_info:
      libraries mkl,vml,guide not found in ['/Users/marc/myenv/lib', '/usr/local/lib', '/usr/lib', '/usr/lib/']
      NOT AVAILABLE

      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in /Users/marc/myenv/lib
      libraries lapack_atlas not found in /Users/marc/myenv/lib
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib/
      libraries lapack_atlas not found in /usr/lib/
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries satlas,satlas not found in /Users/marc/myenv/lib
      libraries lapack_atlas not found in /Users/marc/myenv/lib
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib/
      libraries lapack_atlas not found in /usr/lib/
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in /Users/marc/myenv/lib
      libraries lapack_atlas not found in /Users/marc/myenv/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
      libraries lapack_atlas not found in /usr/lib/
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries f77blas,cblas,atlas not found in /Users/marc/myenv/lib
      libraries lapack_atlas not found in /Users/marc/myenv/lib
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib/
      libraries lapack_atlas not found in /usr/lib/
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

      FOUND:
        extra_compile_args = ['-msse3', '-DAPPLE_ACCELERATE_SGEMV_PATCH']
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3)]

    /usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.macosx-10.11-x86_64-3.5
    creating build/src.macosx-10.11-x86_64-3.5/numpy
    creating build/src.macosx-10.11-x86_64-3.5/numpy/distutils
    building library "npymath" sources
    customize Gnu95FCompiler
    Found executable /usr/local/bin/gfortran
    customize Gnu95FCompiler
    customize Gnu95FCompiler using config
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -c'
    clang: _configtest.c
    clang _configtest.o -o _configtest
    success!
    removing: _configtest.c _configtest.o _configtest
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -c'
    clang: _configtest.c
    _configtest.c:1:5: warning: incompatible redeclaration of library function 'exp' [-Wincompatible-library-redeclaration]
    int exp (void);
        ^
    _configtest.c:1:5: note: 'exp' is a builtin with type 'double (double)'
    1 warning generated.
    clang _configtest.o -o _configtest
    success!
    removing: _configtest.c _configtest.o _configtest
    creating build/src.macosx-10.11-x86_64-3.5/numpy/core
    creating build/src.macosx-10.11-x86_64-3.5/numpy/core/src
    creating build/src.macosx-10.11-x86_64-3.5/numpy/core/src/npymath
    conv_template:> build/src.macosx-10.11-x86_64-3.5/numpy/core/src/npymath/npy_math.c
    conv_template:> build/src.macosx-10.11-x86_64-3.5/numpy/core/src/npymath/ieee754.c
    conv_template:> build/src.macosx-10.11-x86_64-3.5/numpy/core/src/npymath/npy_math_complex.c
    building library "npysort" sources
    creating build/src.macosx-10.11-x86_64-3.5/numpy/core/src/npysort
    conv_template:> build/src.macosx-10.11-x86_64-3.5/numpy/core/src/npysort/quicksort.c
    conv_template:> build/src.macosx-10.11-x86_64-3.5/numpy/core/src/npysort/mergesort.c
    conv_template:> build/src.macosx-10.11-x86_64-3.5/numpy/core/src/npysort/heapsort.c
    creating build/src.macosx-10.11-x86_64-3.5/numpy/core/src/private
    conv_template:> build/src.macosx-10.11-x86_64-3.5/numpy/core/src/private/npy_partition.h
      adding 'build/src.macosx-10.11-x86_64-3.5/numpy/core/src/private' to include_dirs.
    conv_template:> build/src.macosx-10.11-x86_64-3.5/numpy/core/src/npysort/selection.c
    conv_template:> build/src.macosx-10.11-x86_64-3.5/numpy/core/src/private/npy_binsearch.h
    conv_template:> build/src.macosx-10.11-x86_64-3.5/numpy/core/src/npysort/binsearch.c
    None - nothing done with h_files = ['build/src.macosx-10.11-x86_64-3.5/numpy/core/src/private/npy_partition.h', 'build/src.macosx-10.11-x86_64-3.5/numpy/core/src/private/npy_binsearch.h']
    building extension "numpy.core._dummy" sources
    Generating build/src.macosx-10.11-x86_64-3.5/numpy/core/include/numpy/config.h
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

    compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -c'
    clang: _configtest.c
    _configtest.c:1:10: fatal error: 'Python.h' file not found
    #include <Python.h>
             ^
    1 error generated.
    _configtest.c:1:10: fatal error: 'Python.h' file not found
    #include <Python.h>
             ^
    1 error generated.
    failure.
    removing: _configtest.c _configtest.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/setup.py", line 251, in <module>
        setup_package()
      File "/private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/setup.py", line 243, in setup_package
        setup(**metadata)
      File "/private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/numpy/distutils/command/install.py", line 62, in run
        r = self.setuptools_run()
      File "/private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/numpy/distutils/command/install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/numpy/distutils/command/build.py", line 39, in run
        old_build.run(self)
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/numpy/distutils/command/build_src.py", line 153, in run
        self.build_sources()
      File "/private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/numpy/distutils/command/build_src.py", line 170, in build_sources
        self.build_extension_sources(ext)
      File "/private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/numpy/distutils/command/build_src.py", line 329, in build_extension_sources
        sources = self.generate_sources(sources, ext)
      File "/private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/numpy/distutils/command/build_src.py", line 386, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 432, in generate_config_h
        moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)
      File "numpy/core/setup.py", line 42, in check_types
        out = check_types(*a, **kw)
      File "numpy/core/setup.py", line 293, in check_types
        "Cannot compile 'Python.h'. Perhaps you need to "\
    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

    ----------------------------------------
Command "/Users/marc/myenv/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-ik09d_fe-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/marc/myenv/include/site/python3.5/numpy" failed with error code 1 in /private/var/folders/rv/9j67xvf11h33ydhbhk6plgq00000gn/T/pip-build-m_o587dr/numpy/
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
make: *** [sysdeps] Error 1
```

Note: without venv it works. However, I don't want to install neon globally. Any ideas why I'm not able to install numpy using your build script? Installing numpy using `pip install numpy` works in the venv.

**Comment by jennifermyers** [comment]
Hi Marcj,

According to https://github.com/Homebrew/legacy-homebrew/issues/43916 it looks like this issue was fixed in Numpy 1.9.3. 

You should be able to install if you edit the version of numpy in neon/requirements.txt, changing:
numpy==1.9.2
to
numpy==1.9.3

Then rerun make.

This should be fixed also once we release neon 1.6, as we will be bringing numpy up-to-date in this release.

**Comment by jennifermyers** [comment]
Closing this issue as fixed in neon 1.6.0.
