### ISSUE TITLE
No GPU backend when building with anaconda and CUDA 8

### ISSUE THREAD

**Issue by tdeboissiere** [NervanaSystems/neon#293]
I have followed the installation instructions for anaconda.
It builds fine but won't allow me to run on the GPU (only the cpu backend is available).

I have traced this to a pycuda installation error:

$  python -m pycuda.autoinit

Traceback (most recent call last):
  File "/home/tmain/anaconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/tmain/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tmain/anaconda2/lib/python2.7/site-packages/pycuda/autoinit.py", line 2, in <module>
    import pycuda.driver as cuda
  File "/home/tmain/anaconda2/lib/python2.7/site-packages/pycuda/driver.py", line 5, in <module>
    from pycuda._driver import *  # noqa
ImportError: libcurand.so.7.5: cannot open shared object file: No such file or directory

So even if the install detect cuda 8 (which I checked by inspecting the makefile), pycuda is still built assuming cuda 7.5

**Comment by tdeboissiere** [comment]
Fixed this by building pycuda from source and removing the corresponding line in gpu_requirements.txt
