### ISSUE TITLE
ImageLoader: __init__() takes at least 4 arguments (7 given)

### ISSUE THREAD

**Issue by LiyuCode** [NervanaSystems/neon#297]
I was trying to load a macrobatches through ImageLoader while met the error.

### Here is the command to generate the macrobatches
```
python neon/data/batch_writer.py --data_dir ~/data/bot-cv-macrobatch_out \
   --image_dir /home/u/data/BOT-2016-CV-Competition/Data/bot_train \
   --set_type directory \
   --target_size 64 \
   --macro_size 5000 \
   --file_pattern "*.jpg"
```

### Here is the main code that ran:
```
data_dir = 'path-to-macrobatches-folder'
nlabels = 12
subset_pct = 100  

img_set_options = dict(repo_dir=data_dir, nlabels=nlabels, 
                                     macro=True, subset_pct=subset_pct, 
                                     do_transforms=False)
train = ImageLoader(set_name='train', **img_set_options)
test = ImageLoader(set_name='validation', **img_set_options)
```

### then, the error:
```
/usr/bin/python2.7 /home/u/base/code/proj/bot-2016-cv/main.py
Traceback (most recent call last):
  File "/home/u/base/code/proj/bot-2016-cv/main.py", line 12, in <module>
    train = ImageLoader(set_name='train', **img_set_options)
TypeError: __init__() takes at least 4 arguments (7 given)

Process finished with exit code 1
```

Double confirmed the args given are listed in the `__init__` of **ImageLoader**. So I tried online searching for similar cases/reports, but for the most of them, there are less given args than a func takes at least, unlike here. 

Any suggestion?

**Comment by LiyuCode** [comment]
Sorry for the troubles.
Args "inner_size" and "scale_range" has no default value defined in ImageLoader, some one need to pass them to init a ImageLoad instance. One way to do it is add these two args into "img_set_options", after this the error gone.
...However, a new one comes:

```
Traceback (most recent call last):
  File "/home/u/base/code/proj/bot-2016-cv/main.py", line 12, in <module>
    train = ImageLoader(repo_dir=data_dir, set_name='train', **img_set_options)
  File "/usr/local/lib/python2.7/dist-packages/neon/data/imageloader.py", line 118, in __init__
    subset_percent=subset_pct)
  File "/usr/local/lib/python2.7/dist-packages/neon/data/dataloader.py", line 134, in __init__
    self.bsz = self.be.bsz
AttributeError: 'NoneType' object has no attribute 'bsz'
```
working on it...
