### ISSUE TITLE
Can we run two processes on single GPU?

### ISSUE THREAD

**Issue by andyyuan78** [NervanaSystems/neon#30]
while I am running the second phase(training) of 
   neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp32.yaml
I start the first phase of 
    neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp16.yaml
it is OK!

however,
while the second phase of 
    neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp32.yaml
still ongoing,  I launch the second phase of 
    neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp16.yaml
it reports the error:

ubgpu@ubgpu:~/github/neon/neon$ neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp16.yaml
WARNING:neon.util.persist:deserializing object from:  examples/convnet/i1k-alexnet-fp16.yaml
WARNING:neon.datasets.imageset:Imageset initialized with dtype <type 'numpy.float16'>
2015-05-17 14:50:39,937 WARNING:neon - setting log level to: 20
2015-05-17 14:50:40,856 INFO:gpu - Initialized NervanaGPU with stochastic_round=None
2015-05-17 14:50:40,856 INFO:gpu - Seeding random number generator with: None
2015-05-17 14:50:40,857 INFO:__init__ - NervanaGPU backend, RNG seed: None, numerr: None
2015-05-17 14:50:40,858 INFO:mlp - Layers:
        ImageDataLayer d0: 3 x (224 x 224) nodes
        ConvLayer conv1: 3 x (224 x 224) inputs, 64 x (55 x 55) nodes, RectLin act_fn
        PoolingLayer pool1: 64 x (55 x 55) inputs, 64 x (27 x 27) nodes, Linear act_fn
        ConvLayer conv2: 64 x (27 x 27) inputs, 192 x (27 x 27) nodes, RectLin act_fn
        PoolingLayer pool2: 192 x (27 x 27) inputs, 192 x (13 x 13) nodes, Linear act_fn
        ConvLayer conv3: 192 x (13 x 13) inputs, 384 x (13 x 13) nodes, RectLin act_fn
        ConvLayer conv4: 384 x (13 x 13) inputs, 256 x (13 x 13) nodes, RectLin act_fn
        ConvLayer conv5: 256 x (13 x 13) inputs, 256 x (13 x 13) nodes, RectLin act_fn
        PoolingLayer pool3: 256 x (13 x 13) inputs, 256 x (6 x 6) nodes, Linear act_fn
        FCLayer fc4096a: 9216 inputs, 4096 nodes, RectLin act_fn
        DropOutLayer dropout1: 4096 inputs, 4096 nodes, Linear act_fn
        FCLayer fc4096b: 4096 inputs, 4096 nodes, RectLin act_fn
        DropOutLayer dropout2: 4096 inputs, 4096 nodes, Linear act_fn
        FCLayer fc1000: 4096 inputs, 1000 nodes, Softmax act_fn
        CostLayer cost: 1000 nodes, CrossEntropy cost_fn

2015-05-17 14:50:40,858 INFO:batch_norm - BatchNormalization set to train mode
2015-05-17 14:50:40,860 INFO:val_init - Generating AutoUniformValGen values of shape (363, 64)
2015-05-17 14:50:40,862 INFO:batch_norm - BatchNormalization set to train mode
2015-05-17 14:50:40,863 INFO:val_init - Generating AutoUniformValGen values of shape (1600, 192)
2015-05-17 14:50:40,870 INFO:batch_norm - BatchNormalization set to train mode
2015-05-17 14:50:40,871 INFO:val_init - Generating AutoUniformValGen values of shape (1728, 384)
2015-05-17 14:50:40,888 INFO:batch_norm - BatchNormalization set to train mode
2015-05-17 14:50:40,889 INFO:val_init - Generating AutoUniformValGen values of shape (3456, 256)
2015-05-17 14:50:40,914 INFO:batch_norm - BatchNormalization set to train mode
2015-05-17 14:50:40,915 INFO:val_init - Generating AutoUniformValGen values of shape (2304, 256)
2015-05-17 14:50:40,931 INFO:batch_norm - BatchNormalization set to train mode
2015-05-17 14:50:40,932 INFO:val_init - Generating AutoUniformValGen values of shape (4096, 9216)
2015-05-17 14:50:42,483 INFO:batch_norm - BatchNormalization set to train mode
2015-05-17 14:50:42,484 INFO:val_init - Generating AutoUniformValGen values of shape (4096, 4096)
2015-05-17 14:50:43,188 INFO:val_init - Generating AutoUniformValGen values of shape (1000, 4096)
2015-05-17 14:50:43,391 INFO:fit - Unable to find saved model /home/ubgpu/data/I1K/I1K_alexnet_fp16_model.prm, starting over
2015-05-17 14:50:43,393 INFO:mlp - commencing model fitting
Traceback (most recent call last):
  File "/usr/local/bin/neon", line 199, in <module>
    experiment, result, status = main()
  File "/usr/local/bin/neon", line 168, in main
    result = experiment.run()
  File "/usr/local/lib/python2.7/dist-packages/neon/experiments/fit_predict_err.py", line 97, in run
    super(FitPredictErrorExperiment, self).run()
  File "/usr/local/lib/python2.7/dist-packages/neon/experiments/fit.py", line 99, in run
    self.model.fit(self.dataset)
  File "/usr/local/lib/python2.7/dist-packages/neon/models/mlp.py", line 141, in fit
    self.fprop()
  File "/usr/local/lib/python2.7/dist-packages/neon/models/mlp.py", line 81, in fprop
    ll.fprop(y)
  File "/usr/local/lib/python2.7/dist-packages/neon/layers/layer.py", line 373, in fprop
    self.batch_idx)
  File "/usr/local/lib/python2.7/dist-packages/neon/datasets/imageset.py", line 314, in get_mini_batch
    self.backend.subtract(self.inp_be, self.mean_be, self.inp_be)
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/gpu.py", line 643, in subtract
    self.ng.subtract(left, right, out=out)
  File "/usr/local/lib/python2.7/dist-packages/nervanagpu/nervanagpu.py", line 801, in subtract
    def subtract    (self, a, b, out=None): return OpTreeNode.build("sub", a, b, out=out)
  File "/usr/local/lib/python2.7/dist-packages/nervanagpu/nervanagpu.py", line 915, in build
    return OpTreeNode({ "op" : "assign" }, out, node).execute()
  File "/usr/local/lib/python2.7/dist-packages/nervanagpu/nervanagpu.py", line 924, in execute
    return call_compound_kernel(_get_rand_state(), *stack)
  File "/usr/local/lib/python2.7/dist-packages/nervanagpu/float_ew.py", line 835, in call_compound_kernel
    kernel = _get_compound_kernel(tuple(type_args))
  File "<string>", line 2, in _get_compound_kernel
  File "/usr/local/lib/python2.7/dist-packages/pycuda/tools.py", line 423, in context_dependent_memoize
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/nervanagpu/float_ew.py", line 670, in _get_compound_kernel
    module = _get_module(template, template_vals)
  File "/usr/local/lib/python2.7/dist-packages/nervanagpu/float_ew.py", line 313, in _get_module
    return SourceModule(code, options=["--use_fast_math" ], keep=False) #,"-G"
  File "/usr/local/lib/python2.7/dist-packages/pycuda/compiler.py", line 251, in __init__
    arch, code, cache_dir, include_dirs)
  File "/usr/local/lib/python2.7/dist-packages/pycuda/compiler.py", line 241, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir)
  File "/usr/local/lib/python2.7/dist-packages/pycuda/compiler.py", line 73, in compile_plain
    checksum.update(preprocess_source(source, options, nvcc).encode("utf-8"))
  File "/usr/local/lib/python2.7/dist-packages/pycuda/compiler.py", line 47, in preprocess_source
    result, stdout, stderr = call_capture_output(cmdline, error_on_nonzero=False)
  File "/usr/local/lib/python2.7/dist-packages/pytools/prefork.py", line 197, in call_capture_output
    return forker[0].call_capture_output(cmdline, cwd, error_on_nonzero)
  File "/usr/local/lib/python2.7/dist-packages/pytools/prefork.py", line 54, in call_capture_output
    % ( " ".join(cmdline), e))
pytools.prefork.ExecError: error invoking 'nvcc --preprocess --use_fast_math -arch sm_52 -I/usr/local/lib/python2.7/dist-packages/pycuda/cuda /tmp/tmpIRAwNd.cu --compiler-options -P': [Errno 2] No such file or directory
ubgpu@ubgpu:~/github/neon/neon$

**Comment by apark263** [comment]
What are your gpu specs?

If second phase is training, then what do you mean by first phase?

**Comment by andyyuan78** [comment]
my gpu is gtx970

the first phase I means like,  maybe we should call it 'writing batches'

ubgpu@ubgpu:~/github/neon/neon$ neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp16.yaml
WARNING:neon.util.persist:deserializing object from:  examples/convnet/i1k-alexnet-fp16.yaml
WARNING:neon.datasets.imageset:Imageset initialized with dtype <type 'numpy.float16'>
2015-05-16 20:21:56,367 WARNING:neon - setting log level to: 20
2015-05-16 20:21:56,791 INFO:gpu - Initialized NervanaGPU with stochastic_round=None
2015-05-16 20:21:56,791 INFO:gpu - Seeding random number generator with: None
2015-05-16 20:21:56,792 INFO:__init__ - NervanaGPU backend, RNG seed: None, numerr: None
2015-05-16 20:21:56,793 INFO:mlp - Layers:
        ImageDataLayer d0: 3 x (224 x 224) nodes
        ConvLayer conv1: 3 x (224 x 224) inputs, 64 x (55 x 55) nodes, RectLin act_fn
        PoolingLayer pool1: 64 x (55 x 55) inputs, 64 x (27 x 27) nodes, Linear act_fn
        ConvLayer conv2: 64 x (27 x 27) inputs, 192 x (27 x 27) nodes, RectLin act_fn
        PoolingLayer pool2: 192 x (27 x 27) inputs, 192 x (13 x 13) nodes, Linear act_fn
        ConvLayer conv3: 192 x (13 x 13) inputs, 384 x (13 x 13) nodes, RectLin act_fn
        ConvLayer conv4: 384 x (13 x 13) inputs, 256 x (13 x 13) nodes, RectLin act_fn
        ConvLayer conv5: 256 x (13 x 13) inputs, 256 x (13 x 13) nodes, RectLin act_fn
        PoolingLayer pool3: 256 x (13 x 13) inputs, 256 x (6 x 6) nodes, Linear act_fn
        FCLayer fc4096a: 9216 inputs, 4096 nodes, RectLin act_fn
        DropOutLayer dropout1: 4096 inputs, 4096 nodes, Linear act_fn
        FCLayer fc4096b: 4096 inputs, 4096 nodes, RectLin act_fn
        DropOutLayer dropout2: 4096 inputs, 4096 nodes, Linear act_fn
        FCLayer fc1000: 4096 inputs, 1000 nodes, Softmax act_fn
        CostLayer cost: 1000 nodes, CrossEntropy cost_fn

2015-05-16 20:21:56,793 INFO:batch_norm - BatchNormalization set to train mode
2015-05-16 20:21:56,794 INFO:val_init - Generating AutoUniformValGen values of shape (363, 64)
2015-05-16 20:21:56,796 INFO:batch_norm - BatchNormalization set to train mode
2015-05-16 20:21:56,797 INFO:val_init - Generating AutoUniformValGen values of shape (1600, 192)
2015-05-16 20:21:56,803 INFO:batch_norm - BatchNormalization set to train mode
2015-05-16 20:21:56,804 INFO:val_init - Generating AutoUniformValGen values of shape (1728, 384)
2015-05-16 20:21:56,815 INFO:batch_norm - BatchNormalization set to train mode
2015-05-16 20:21:56,816 INFO:val_init - Generating AutoUniformValGen values of shape (3456, 256)
2015-05-16 20:21:56,830 INFO:batch_norm - BatchNormalization set to train mode
2015-05-16 20:21:56,831 INFO:val_init - Generating AutoUniformValGen values of shape (2304, 256)
2015-05-16 20:21:56,841 INFO:batch_norm - BatchNormalization set to train mode
2015-05-16 20:21:56,842 INFO:val_init - Generating AutoUniformValGen values of shape (4096, 9216)
2015-05-16 20:21:57,386 INFO:batch_norm - BatchNormalization set to train mode
2015-05-16 20:21:57,387 INFO:val_init - Generating AutoUniformValGen values of shape (4096, 4096)
2015-05-16 20:21:57,628 INFO:val_init - Generating AutoUniformValGen values of shape (1000, 4096)
2015-05-16 20:21:57,688 WARNING:imageset - Batch dir cache not found in /home/ubgpu/data/I1K/imageset_batches_16/dataset_cache.pkl:
Press Y to create, otherwise exit: Y
2015-05-16 20:22:04,634 INFO:batch_writer - Loaded synset tars.
2015-05-16 20:22:04,634 INFO:batch_writer - Building trainset list ( can take a while)...
2015-05-16 20:22:04,634 INFO:batch_writer - 0% ...
2015-05-16 20:24:16,828 INFO:batch_writer - 10% ...
2015-05-16 20:25:50,283 INFO:batch_writer - 20% ...
2015-05-16 20:27:43,577 INFO:batch_writer - 30% ...
2015-05-16 20:29:44,691 INFO:batch_writer - 40% ...
2015-05-16 20:31:35,079 INFO:batch_writer - 50% ...
...............
2015-05-17 03:27:14,005 WARNING:persist - serializing object to: /home/ubgpu/data/I1K/imageset_batches_16/dataset_cache.pkl
2015-05-17 03:27:21,257 WARNING:imageset - Done writing batches - please rerun to train.
ubgpu@ubgpu:~/github/neon/neon$
                                                                                                   

****************************************************************************************

here are the resource while runing the second phase of
    neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp32.yaml
ubgpu@ubgpu:~$ nvidia-smi
Sun May 17 15:13:37 2015       
+------------------------------------------------------+                       
| NVIDIA-SMI 346.46     Driver Version: 346.46         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 970     Off  | 0000:01:00.0     N/A |                  N/A |
| 62%   70C    P2    N/A /  N/A |   1817MiB /  4095MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0            C+G   Not Supported                                         |
+-----------------------------------------------------------------------------+
ubgpu@ubgpu:~$

**Comment by apark263** [comment]
You shouldn't need to write batches again for fp16. Both formats are
intended to use the same underlying data.

Can you run nvidia-smi when just the fp32 version is in training mode to
see how much memory is being used?

Also, sgray says you will probably get better overall performance by
running the two training runs serially rather than in parallel.  Just in
case you are holding off on training while waiting to be able to get
parallel working.

**Comment by andyyuan78** [comment]
| 0 GeForce GTX 970 Off | 0000:01:00.0 N/A | N/A |
 | 62% 70C P2 N/A / N/A | 1817MiB / 4095MiB | N/A Default |


the above is the result of nvidia-smi while  just the fp32 version is in training mode .

just test it can be parallel!

**Comment by andyyuan78** [comment]
it works well in 'paraller' with tow process like
neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp32.yaml
 neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp16.yaml

The error happens due to someone delete the bin/nvcc
