### ISSUE TITLE
Fatal Error in MacOS Sierra when running 'make' after installing dependencies

### ISSUE THREAD

**Issue by shyamalschandra** [NervanaSystems/neon#305]
Where do I find the libavformat.h because I have already install ffmpeg using homebrew in order to make neon build properly on Sierra?

```
iMac:neon shyamalsuhanachandra$ make
Updating virtualenv dependencies in: .venv2...
Running virtualenv with interpreter /usr/local/bin/python2.7
New python executable in /Users/shyamalsuhanachandra/neon/.venv2/bin/python2.7
Also creating executable in /Users/shyamalsuhanachandra/neon/.venv2/bin/python
Installing setuptools, pip, wheel...done.
Requirement already up-to-date: pip in ./.venv2/lib/python2.7/site-packages
Collecting cython==0.23.1
  Downloading Cython-0.23.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.8MB)
    100% |████████████████████████████████| 3.9MB 371kB/s 
Installing collected packages: cython
Successfully installed cython-0.23.1
Collecting configargparse==0.10.0 (from -r requirements.txt (line 1))
  Downloading ConfigArgParse-0.10.0.tar.gz
Collecting numpy==1.11.1 (from -r requirements.txt (line 2))
  Downloading numpy-1.11.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.9MB)
    100% |████████████████████████████████| 3.9MB 343kB/s 
Collecting pyyaml==3.12 (from -r requirements.txt (line 3))
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 954kB/s 
Collecting pep8==1.7.0 (from -r requirements.txt (line 4))
  Downloading pep8-1.7.0-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 8.7MB/s 
Collecting flake8==3.0.4 (from -r requirements.txt (line 5))
  Downloading flake8-3.0.4-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 7.2MB/s 
Collecting pytest==3.0.1 (from -r requirements.txt (line 6))
  Downloading pytest-3.0.1-py2.py3-none-any.whl (169kB)
    100% |████████████████████████████████| 174kB 3.7MB/s 
Collecting pytest-cov==2.3.1 (from -r requirements.txt (line 7))
  Downloading pytest_cov-2.3.1-py2.py3-none-any.whl
Collecting posix_ipc==1.0.0 (from -r requirements.txt (line 8))
  Downloading posix_ipc-1.0.0-cp27-cp27m-macosx_10_6_x86_64.whl
Collecting pillow==3.3.1 (from -r requirements.txt (line 9))
  Downloading Pillow-3.3.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.1MB)
    100% |████████████████████████████████| 3.1MB 406kB/s 
Collecting pylint==1.6.4 (from -r requirements.txt (line 10))
  Downloading pylint-1.6.4-py2.py3-none-any.whl (569kB)
    100% |████████████████████████████████| 573kB 1.4MB/s 
Collecting sphinx==1.4.6 (from -r requirements.txt (line 11))
  Downloading Sphinx-1.4.6-py2.py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 664kB/s 
Collecting h5py==2.6.0 (from -r requirements.txt (line 12))
  Downloading h5py-2.6.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.5MB)
    100% |████████████████████████████████| 4.5MB 295kB/s 
Collecting appdirs==1.4.0 (from -r requirements.txt (line 13))
  Downloading appdirs-1.4.0-py2.py3-none-any.whl
Collecting future==0.15.2 (from -r requirements.txt (line 14))
  Downloading future-0.15.2.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 798kB/s 
Collecting enum34; python_version < "3.4" (from flake8==3.0.4->-r requirements.txt (line 5))
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting configparser; python_version < "3.2" (from flake8==3.0.4->-r requirements.txt (line 5))
  Downloading configparser-3.5.0.tar.gz
Collecting mccabe<0.6.0,>=0.5.0 (from flake8==3.0.4->-r requirements.txt (line 5))
  Downloading mccabe-0.5.2-py2.py3-none-any.whl
Collecting pycodestyle<2.1.0,>=2.0.0 (from flake8==3.0.4->-r requirements.txt (line 5))
  Downloading pycodestyle-2.0.0-py2.py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 5.3MB/s 
Collecting pyflakes!=1.2.0,!=1.2.1,!=1.2.2,<1.3.0,>=0.8.1 (from flake8==3.0.4->-r requirements.txt (line 5))
  Downloading pyflakes-1.2.3-py2.py3-none-any.whl (209kB)
    100% |████████████████████████████████| 215kB 1.8MB/s 
Collecting py>=1.4.29 (from pytest==3.0.1->-r requirements.txt (line 6))
  Downloading py-1.4.31-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 92kB 8.7MB/s 
Collecting coverage>=3.7.1 (from pytest-cov==2.3.1->-r requirements.txt (line 7))
  Downloading coverage-4.2-cp27-cp27m-macosx_10_10_x86_64.whl (161kB)
    100% |████████████████████████████████| 163kB 3.6MB/s 
Collecting astroid<1.5.0,>=1.4.5 (from pylint==1.6.4->-r requirements.txt (line 10))
  Downloading astroid-1.4.8-py2.py3-none-any.whl (213kB)
    100% |████████████████████████████████| 215kB 1.5MB/s 
Collecting isort>=4.2.5 (from pylint==1.6.4->-r requirements.txt (line 10))
  Downloading isort-4.2.5-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 7.7MB/s 
Collecting six (from pylint==1.6.4->-r requirements.txt (line 10))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting backports.functools-lru-cache; python_version == "2.7" (from pylint==1.6.4->-r requirements.txt (line 10))
  Downloading backports.functools_lru_cache-1.2.1-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading Pygments-2.1.3-py2.py3-none-any.whl (755kB)
    100% |████████████████████████████████| 757kB 1.5MB/s 
Collecting docutils>=0.11 (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading docutils-0.12.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 683kB/s 
Collecting alabaster<0.8,>=0.7 (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading alabaster-0.7.9-py2.py3-none-any.whl
Collecting Jinja2>=2.3 (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 2.3MB/s 
Collecting snowballstemmer>=1.1 (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading snowballstemmer-1.2.1-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 8.0MB/s 
Collecting babel!=2.0,>=1.3 (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading Babel-2.3.4-py2.py3-none-any.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 174kB/s 
Collecting imagesize (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading imagesize-0.7.1-py2.py3-none-any.whl
Collecting lazy-object-proxy (from astroid<1.5.0,>=1.4.5->pylint==1.6.4->-r requirements.txt (line 10))
  Downloading lazy-object-proxy-1.2.2.tar.gz
Collecting wrapt (from astroid<1.5.0,>=1.4.5->pylint==1.6.4->-r requirements.txt (line 10))
  Downloading wrapt-1.10.8.tar.gz
Collecting MarkupSafe (from Jinja2>=2.3->sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading MarkupSafe-0.23.tar.gz
Collecting pytz>=0a (from babel!=2.0,>=1.3->sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading pytz-2016.6.1-py2.py3-none-any.whl (481kB)
    100% |████████████████████████████████| 481kB 2.1MB/s 
Building wheels for collected packages: configargparse, pyyaml, future, configparser, docutils, lazy-object-proxy, wrapt, MarkupSafe
  Running setup.py bdist_wheel for configargparse ... done
  Stored in directory: /Users/shyamalsuhanachandra/Library/Caches/pip/wheels/1e/2a/b6/4a95a72c4f9caf9d2a8873487ea7a65f7e46a1133a75df9856
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /Users/shyamalsuhanachandra/Library/Caches/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /Users/shyamalsuhanachandra/Library/Caches/pip/wheels/11/c5/d2/ad287de27d0f0d646f119dcffb921f4e63df128f28ab0a1bda
  Running setup.py bdist_wheel for configparser ... done
  Stored in directory: /Users/shyamalsuhanachandra/Library/Caches/pip/wheels/1c/bd/b4/277af3f6c40645661b4cd1c21df26aca0f2e1e9714a1d4cda8
  Running setup.py bdist_wheel for docutils ... done
  Stored in directory: /Users/shyamalsuhanachandra/Library/Caches/pip/wheels/db/de/bd/b99b1e12d321fbc950766c58894c6576b1a73ae3131b29a151
  Running setup.py bdist_wheel for lazy-object-proxy ... done
  Stored in directory: /Users/shyamalsuhanachandra/Library/Caches/pip/wheels/06/d4/af/71508d0c69292f8c369ba3ae83cd85fabcd6956fd5709633b4
  Running setup.py bdist_wheel for wrapt ... done
  Stored in directory: /Users/shyamalsuhanachandra/Library/Caches/pip/wheels/19/8a/01/20cf74c3f38d49ef8e9b9aa7ffd38cefff79bad9f6f2c651f0
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /Users/shyamalsuhanachandra/Library/Caches/pip/wheels/a3/fa/dc/0198eed9ad95489b8a4f45d14dd5d2aee3f8984e46862c5748
Successfully built configargparse pyyaml future configparser docutils lazy-object-proxy wrapt MarkupSafe
Installing collected packages: configargparse, numpy, pyyaml, pep8, enum34, configparser, mccabe, pycodestyle, pyflakes, flake8, py, pytest, coverage, pytest-cov, posix-ipc, pillow, six, lazy-object-proxy, wrapt, astroid, isort, backports.functools-lru-cache, pylint, Pygments, docutils, alabaster, MarkupSafe, Jinja2, snowballstemmer, pytz, babel, imagesize, sphinx, h5py, appdirs, future
Successfully installed Jinja2-2.8 MarkupSafe-0.23 Pygments-2.1.3 alabaster-0.7.9 appdirs-1.4.0 astroid-1.4.8 babel-2.3.4 backports.functools-lru-cache-1.2.1 configargparse-0.10.0 configparser-3.5.0 coverage-4.2 docutils-0.12 enum34-1.1.6 flake8-3.0.4 future-0.15.2 h5py-2.6.0 imagesize-0.7.1 isort-4.2.5 lazy-object-proxy-1.2.2 mccabe-0.5.2 numpy-1.11.1 pep8-1.7.0 pillow-3.3.1 posix-ipc-1.0.0 py-1.4.31 pycodestyle-2.0.0 pyflakes-1.2.3 pylint-1.6.4 pytest-3.0.1 pytest-cov-2.3.1 pytz-2016.6.1 pyyaml-3.12 six-1.10.0 snowballstemmer-1.2.1 sphinx-1.4.6 wrapt-1.10.8

Installing neon in development mode...
running develop
running egg_info
creating neon.egg-info
writing neon.egg-info/PKG-INFO
writing top-level names to neon.egg-info/top_level.txt
writing dependency_links to neon.egg-info/dependency_links.txt
writing manifest file 'neon.egg-info/SOURCES.txt'
reading manifest file 'neon.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'neon.egg-info/SOURCES.txt'
running build_ext
Creating /Users/shyamalsuhanachandra/neon/.venv2/lib/python2.7/site-packages/neon.egg-link (link to .)
Adding neon 1.6.0 to easy-install.pth file
Installing neon script to /Users/shyamalsuhanachandra/neon/.venv2/bin
Installing nvis script to /Users/shyamalsuhanachandra/neon/.venv2/bin

Installed /Users/shyamalsuhanachandra/neon
Processing dependencies for neon==1.6.0
Finished processing dependencies for neon==1.6.0
###########################################################
Setup complete.  Type:
    . '.venv2/bin/activate'
to work interactively (.venv2 also symlinked to .venv)
###########################################################

Building bin/loader.so...
g++ -shared -o bin/loader.so -fPIC -Wall -Wno-deprecated-declarations -O3 -std=c++11  -DHAS_IMGLIB -DHAS_VIDLIB -DHAS_AUDLIB src/loader.cpp -I/usr/local/Cellar/opencv/2.4.12_2/include/opencv -I/usr/local/Cellar/opencv/2.4.12_2/include -L/usr/local/Cellar/opencv/2.4.12_2/lib -L/usr/local/Cellar/ffmpeg/3.0.1/lib -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab -lavutil -lavformat -lavcodec -lswscale
In file included from src/loader.cpp:26:
src/video.hpp:28:14: fatal error: 'libavformat/avformat.h' file not found
    #include <libavformat/avformat.h>
             ^
1 error generated.
make[1]: *** [bin/loader.so] Error 1
make: [loader] Error 2 (ignored)
```

**Comment by anlthms** [comment]
Thanks for reporting this. This patch should fix the problem that you are seeing:

```
--- a/loader/Makefile
+++ b/loader/Makefile
@@ -34,6 +34,7 @@ ifeq ($(shell pkg-config --exists opencv; echo $$?), 0)
 ifeq ($(shell pkg-config --exists libavutil libavformat libavcodec libswscale; echo $$?), 0)
        VIDFLAG     := -DHAS_VIDLIB
        AUDFLAG     := -DHAS_AUDLIB
+       INC         := $(shell pkg-config --cflags libavutil libavformat libavcodec libswscale) $(INC)
        VIDLDIR     := $(shell pkg-config --libs-only-L libavutil libavformat libavcodec libswscale)
        VIDLIBS     := -lavutil -lavformat -lavcodec -lswscale
 endif
```

Please add the line shown in the above patch to neon/loader/Makefile and then try running make again.

**Comment by shyamalschandra** [comment]
@anlthms : Could you tell the exact steps to apply this patch?  Thanks!

**Comment by anlthms** [comment]
@shyamalschandra, add the following line inside neon/loader/Makefile at the location shown by the diff above:

       INC         := $(shell pkg-config --cflags libavutil libavformat libavcodec libswscale) $(INC)

This should take care of the compiler error that you were seeing. Let us know if this works for you.

**Comment by weibogit** [comment]
I had tried @anlthms  solution, but it still has some problems. I can use neon in terminal, but in Spyder IDE, it can not import neon. And, I have tried to "source activate". So, please give me a help. Details as follow scripts.

###########edit Makefile as you(@anlthms) said above###########################
weibo@ubuntu:/opt/neon$ cd /opt/neon/loader
weibo@ubuntu:/opt/neon/loader$ sudo vim Makefile       # add "INC....."line
weibo@ubuntu:/opt/neon/loader$ cd /opt/neon/


############ install neon with python2#############################
weibo@ubuntu:/opt/neon$ sudo make python2
Updating virtualenv dependencies in: .venv2...
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /opt/neon/.venv2/bin/python2.7
Also creating executable in /opt/neon/.venv2/bin/python
Installing setuptools, pip, wheel...done.
The directory '/home/weibo/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/weibo/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pip in ./.venv2/lib/python2.7/site-packages
The directory '/home/weibo/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/weibo/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting cython==0.23.1
  Downloading Cython-0.23.1-cp27-cp27mu-manylinux1_x86_64.whl (5.6MB)
    100% |████████████████████████████████| 5.6MB 150kB/s 
Installing collected packages: cython
Successfully installed cython-0.23.1
The directory '/home/weibo/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/weibo/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting configargparse==0.10.0 (from -r requirements.txt (line 1))
  Downloading ConfigArgParse-0.10.0.tar.gz
Collecting numpy==1.11.1 (from -r requirements.txt (line 2))
  Downloading numpy-1.11.1-cp27-cp27mu-manylinux1_x86_64.whl (15.3MB)
    100% |████████████████████████████████| 15.3MB 63kB/s 
Collecting pyyaml==3.12 (from -r requirements.txt (line 3))
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 949kB/s 
Collecting pep8==1.7.0 (from -r requirements.txt (line 4))
  Downloading pep8-1.7.0-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 2.0MB/s 
Collecting flake8==3.0.4 (from -r requirements.txt (line 5))
  Downloading flake8-3.0.4-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 1.5MB/s 
Collecting pytest==3.0.1 (from -r requirements.txt (line 6))
  Downloading pytest-3.0.1-py2.py3-none-any.whl (169kB)
    100% |████████████████████████████████| 174kB 2.2MB/s 
Collecting pytest-cov==2.3.1 (from -r requirements.txt (line 7))
  Downloading pytest_cov-2.3.1-py2.py3-none-any.whl
Collecting posix_ipc==1.0.0 (from -r requirements.txt (line 8))
  Downloading posix_ipc-1.0.0.tar.gz (74kB)
    100% |████████████████████████████████| 81kB 981kB/s 
Collecting pillow==3.3.1 (from -r requirements.txt (line 9))
  Downloading Pillow-3.3.1-cp27-cp27mu-manylinux1_x86_64.whl (5.6MB)
    100% |████████████████████████████████| 5.6MB 148kB/s 
Collecting pylint==1.6.4 (from -r requirements.txt (line 10))
  Downloading pylint-1.6.4-py2.py3-none-any.whl (569kB)
    100% |████████████████████████████████| 573kB 305kB/s 
Collecting sphinx==1.4.6 (from -r requirements.txt (line 11))
  Downloading Sphinx-1.4.6-py2.py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 334kB/s 
Collecting h5py==2.6.0 (from -r requirements.txt (line 12))
  Downloading h5py-2.6.0-1-cp27-cp27mu-manylinux1_x86_64.whl (4.2MB)
    100% |████████████████████████████████| 4.2MB 194kB/s 
Collecting appdirs==1.4.0 (from -r requirements.txt (line 13))
  Downloading appdirs-1.4.0-py2.py3-none-any.whl
Collecting future==0.15.2 (from -r requirements.txt (line 14))
  Downloading future-0.15.2.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 124kB/s 
Collecting enum34; python_version < "3.4" (from flake8==3.0.4->-r requirements.txt (line 5))
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting configparser; python_version < "3.2" (from flake8==3.0.4->-r requirements.txt (line 5))
  Downloading configparser-3.5.0.tar.gz
Collecting mccabe<0.6.0,>=0.5.0 (from flake8==3.0.4->-r requirements.txt (line 5))
  Downloading mccabe-0.5.2-py2.py3-none-any.whl
Collecting pycodestyle<2.1.0,>=2.0.0 (from flake8==3.0.4->-r requirements.txt (line 5))
  Downloading pycodestyle-2.0.0-py2.py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 816kB/s 
Collecting pyflakes!=1.2.0,!=1.2.1,!=1.2.2,<1.3.0,>=0.8.1 (from flake8==3.0.4->-r requirements.txt (line 5))
  Downloading pyflakes-1.2.3-py2.py3-none-any.whl (209kB)
    100% |████████████████████████████████| 215kB 379kB/s 
Collecting py>=1.4.29 (from pytest==3.0.1->-r requirements.txt (line 6))
  Downloading py-1.4.31-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 92kB 789kB/s 
Collecting coverage>=3.7.1 (from pytest-cov==2.3.1->-r requirements.txt (line 7))
  Downloading coverage-4.2.tar.gz (359kB)
    100% |████████████████████████████████| 368kB 449kB/s 
Collecting six (from pylint==1.6.4->-r requirements.txt (line 10))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting astroid<1.5.0,>=1.4.5 (from pylint==1.6.4->-r requirements.txt (line 10))
  Downloading astroid-1.4.8-py2.py3-none-any.whl (213kB)
    100% |████████████████████████████████| 215kB 662kB/s 
Collecting isort>=4.2.5 (from pylint==1.6.4->-r requirements.txt (line 10))
  Downloading isort-4.2.5-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 2.3MB/s 
Collecting backports.functools-lru-cache; python_version == "2.7" (from pylint==1.6.4->-r requirements.txt (line 10))
  Downloading backports.functools_lru_cache-1.2.1-py2.py3-none-any.whl
Collecting babel!=2.0,>=1.3 (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading Babel-2.3.4-py2.py3-none-any.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 129kB/s 
Collecting imagesize (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading imagesize-0.7.1-py2.py3-none-any.whl
Collecting Pygments>=2.0 (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading Pygments-2.1.3-py2.py3-none-any.whl (755kB)
    100% |████████████████████████████████| 757kB 383kB/s 
Collecting docutils>=0.11 (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading docutils-0.12.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 349kB/s 
Collecting alabaster<0.8,>=0.7 (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading alabaster-0.7.9-py2.py3-none-any.whl
Collecting Jinja2>=2.3 (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 619kB/s 
Collecting snowballstemmer>=1.1 (from sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading snowballstemmer-1.2.1-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 1.5MB/s 
Collecting lazy-object-proxy (from astroid<1.5.0,>=1.4.5->pylint==1.6.4->-r requirements.txt (line 10))
  Downloading lazy_object_proxy-1.2.2-cp27-cp27mu-manylinux1_x86_64.whl (56kB)
    100% |████████████████████████████████| 61kB 1.2MB/s 
Collecting wrapt (from astroid<1.5.0,>=1.4.5->pylint==1.6.4->-r requirements.txt (line 10))
  Downloading wrapt-1.10.8.tar.gz
Collecting pytz>=0a (from babel!=2.0,>=1.3->sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading pytz-2016.6.1-py2.py3-none-any.whl (481kB)
    100% |████████████████████████████████| 481kB 573kB/s 
Collecting MarkupSafe (from Jinja2>=2.3->sphinx==1.4.6->-r requirements.txt (line 11))
  Downloading MarkupSafe-0.23.tar.gz
Installing collected packages: configargparse, numpy, pyyaml, pep8, enum34, configparser, mccabe, pycodestyle, pyflakes, flake8, py, pytest, coverage, pytest-cov, posix-ipc, pillow, six, lazy-object-proxy, wrapt, astroid, isort, backports.functools-lru-cache, pylint, pytz, babel, imagesize, Pygments, docutils, alabaster, MarkupSafe, Jinja2, snowballstemmer, sphinx, h5py, appdirs, future
  Running setup.py install for configargparse ... done
  Running setup.py install for pyyaml ... done
  Running setup.py install for configparser ... done
  Running setup.py install for coverage ... done
  Running setup.py install for posix-ipc ... done
  Running setup.py install for wrapt ... done
  Running setup.py install for docutils ... done
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for future ... done
Successfully installed Jinja2-2.8 MarkupSafe-0.23 Pygments-2.1.3 alabaster-0.7.9 appdirs-1.4.0 astroid-1.4.8 babel-2.3.4 backports.functools-lru-cache-1.2.1 configargparse-0.10.0 configparser-3.5.0 coverage-4.2 docutils-0.12 enum34-1.1.6 flake8-3.0.4 future-0.15.2 h5py-2.6.0 imagesize-0.7.1 isort-4.2.5 lazy-object-proxy-1.2.2 mccabe-0.5.2 numpy-1.11.1 pep8-1.7.0 pillow-3.3.1 posix-ipc-1.0.0 py-1.4.31 pycodestyle-2.0.0 pyflakes-1.2.3 pylint-1.6.4 pytest-3.0.1 pytest-cov-2.3.1 pytz-2016.6.1 pyyaml-3.12 six-1.10.0 snowballstemmer-1.2.1 sphinx-1.4.6 wrapt-1.10.8

Installing neon in development mode...
running develop
running egg_info
creating neon.egg-info
writing neon.egg-info/PKG-INFO
writing top-level names to neon.egg-info/top_level.txt
writing dependency_links to neon.egg-info/dependency_links.txt
writing manifest file 'neon.egg-info/SOURCES.txt'
reading manifest file 'neon.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'neon.egg-info/SOURCES.txt'
running build_ext
Creating /opt/neon/.venv2/lib/python2.7/site-packages/neon.egg-link (link to .)
Adding neon 1.6.0 to easy-install.pth file
Installing neon script to /opt/neon/.venv2/bin
Installing nvis script to /opt/neon/.venv2/bin

Installed /opt/neon
Processing dependencies for neon==1.6.0
Finished processing dependencies for neon==1.6.0
###########################################################
Setup complete.  Type:
    . '.venv2/bin/activate'
to work interactively (.venv2 also symlinked to .venv)
###########################################################

make[1]: Entering directory '/opt/neon/loader'
Building bin/loader.so...
g++ -shared -o bin/loader.so -fPIC -Wall -Wno-deprecated-declarations -O3 -std=c++11  -DHAS_IMGLIB   src/loader.cpp -I/usr/local/include/opencv -I/usr/local/include -L/usr/local/lib  -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab -lrt -lpthread -lm -ldl 
make[1]: Leaving directory '/opt/neon/loader'
weibo@ubuntu:/opt/neon$ . .venv/bin/activate
(.venv2) weibo@ubuntu:/opt/neon$ sudo neon examples/mnist_mlp.yaml
sudo：neon: command not found
(.venv2) weibo@ubuntu:/opt/neon$ neon examples/mnist_mlp.yaml
2016-09-30 11:16:37,271 - neon - DISPLAY - Downloading file: ./mnist.pkl.gz
Traceback (most recent call last):
  File "/opt/neon/.venv2/bin/neon", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/neon/bin/neon", line 147, in <module>
    train, test = load_data(data_dir=args.data_dir)
  File "/opt/neon/bin/neon", line 126, in load_data
    dataiters = dataset.gen_iterators()
  File "/opt/neon/neon/data/image.py", line 78, in gen_iterators
    (X_train, y_train), (X_test, y_test), nclass = self.load_data()
  File "/opt/neon/neon/data/image.py", line 64, in load_data
    self.fetch_dataset(self.url, self.filename, filepath, self.size)
  File "/opt/neon/neon/data/datasets.py", line 137, in fetch_dataset
    with open(destfile, 'wb') as f:
IOError: [Errno 13] Permission denied: './mnist.pkl.gz'

############# in terminal, there is no error report #####################
**(.venv2) weibo@ubuntu:/opt/neon$ python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import neon
>>> help(neon)**


############## in spyder IDE###################

Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
**>>> import neon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named neon**

**Comment by hanlin-nervana** [comment]
I am not familiar with spyder IDE, but likely there is a virtualenv setting needed somewhere (or sypder need to be installed in and run from your virtualenv). These may be relevant: 

http://stackoverflow.com/questions/28190500/virtualenv-ipython-in-spyder-not-working
http://stackoverflow.com/questions/30170468/how-to-run-spyder-in-virtual-environment
