### ISSUE TITLE
Error running ./examples/cifar10_msra.py

### ISSUE THREAD

**Issue by ternaus** [NervanaSystems/neon#308]
ubuntu 16.04
cuda 8.0
TITAN X (Pascal)
neon 1.6.0 

No errors with cifar10_conv.py, but with cifar10_msra.py:

``` 
./examples/cifar10_msra.py -e1
Traceback (most recent call last):
  File "./examples/cifar10_msra.py", line 146, in <module>
    shuffle=True, subset_percent=args.subset_pct, **common)
  File "/home/vladimir/packages/neon/neon/data/dataloader.py", line 168, in __init__
    self.load_library()
  File "/home/vladimir/packages/neon/neon/data/dataloader.py", line 177, in load_library
    self.loaderlib = ct.cdll.LoadLibrary(libpath)
  File "/home/vladimir/anaconda2/envs/neon/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/home/vladimir/anaconda2/envs/neon/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/vladimir/packages/neon/neon/data/../../loader/bin/loader.so: undefined symbol: _ZN2cv8fastFreeEPv
```

**Comment by anlthms** [comment]
Please give this a try:

Replace this line inside neon/loader/Makefile
       IMGLIBS     := $(shell pkg-config --libs-only-l opencv)
with 
       IMGLIBS     := $(shell pkg-config --libs opencv)
and then issue this command from the top level neon directory:
make -C loader clean && make

**Comment by ternaus** [comment]
Thank you. This solved the problem.
