### ISSUE TITLE
Training Faster-RCNN on GPU causes AssertionError: N dim must be multiple of 32

### ISSUE THREAD

**Issue by Nr90** [NervanaSystems/neon#318]
When running the faster-rcnn train example on an amazon G2 instance on gpu I get the following error:

```
Traceback (most recent call last):
  File "examples/faster-rcnn/train.py", line 106, in <module>
    model.fit(train_set, optimizer=optimizer, cost=cost, num_epochs=args.epochs, ca
llbacks=callbacks)
  File "/root/neon/neon/models/model.py", line 167, in fit
    self.initialize(dataset, cost)
  File "/root/neon/neon/models/model.py", line 114, in initialize
    prev_input = self.layers.configure(prev_input)
  File "/root/neon/neon/layers/container.py", line 440, in configure
    self.layers[0].configure(in_obj)
  File "/root/neon/neon/layers/container.py", line 273, in configure
    in_obj = l.configure(in_obj)
  File "/root/neon/neon/layers/layer.py", line 760, in configure
    self.nglayer = self.be.conv_layer(self.be.default_dtype, **self.convparams)
  File "/root/neon/neon/backends/nervanagpu.py", line 1912, in conv_layer
    pad_d, pad_h, pad_w, str_d, str_h, str_w)
  File "/root/neon/neon/backends/layer_gpu.py", line 415, in __init__
    self.fprop_kernels = convolution.FpropCuda(*args)
  File "/root/neon/neon/backends/convolution.py", line 131, in __init__
    assert N % 32 == 0, "N dim must be multiple of 32"
AssertionError: N dim must be multiple of 32
```

On cpu the error does not occur.
Am I simply running out of GPU memory or is something else wrong?

**Comment by yinyinl** [comment]
The amazon G2 instances use kepler-based GPUs. While neon does provide support on pre-Maxwell GPUs for most of the kernels, but the ones needed by Faster RCNN model (minibatch size N = 1) currently are not available.

**Comment by Nr90** [comment]
Thank you for the quick response!

**Comment by ronilp** [comment]
Will Nvidia K80 GPUs work with faster rcnn?

**Comment by yinyinl** [comment]
The K80 GPUs are kepler-based ones. So no, for the reason above. Thanks.
