### ISSUE TITLE
Can't run mobydick-lstm-small.yaml example on GPU

### ISSUE THREAD

**Issue by shuokay** [NervanaSystems/neon#32]
I have a K40, and the install neon succeed.
I have tested the installation by run the mnist-small.yaml on GPU and here is the output. I think I have installed neon succeed.
```
(venv)↪  /home/gys/ocz/NervanaSys/neon/examples/convnet git:(master) ▸
↪  neon -g cudanet mnist-small.yaml
WARNING:neon.util.persist:deserializing object from:  mnist-small.yaml
2015-05-18 14:38:13,823 WARNING:neon - setting log level to: 20
2015-05-18 14:38:14,048 INFO:__init__ - Cudanet backend, RNG seed: None, numerr: None
2015-05-18 14:38:14,049 INFO:mlp - Layers:
        DataLayer d0: 784 nodes
        ConvLayer layer1: 1 x (28 x 28) inputs, 16 x (24 x 24) nodes, Linear act_fn
        PoolingLayer layer2: 16 x (24 x 24) inputs, 16 x (12 x 12) nodes, Linear act_fn
        ConvLayer layer3: 16 x (12 x 12) inputs, 32 x (8 x 8) nodes, Linear act_fn
        PoolingLayer layer4: 32 x (8 x 8) inputs, 32 x (4 x 4) nodes, Linear act_fn
        FCLayer layer5: 512 inputs, 500 nodes, RectLin act_fn
        FCLayer output: 500 inputs, 10 nodes, Logistic act_fn
        CostLayer cost: 10 nodes, CrossEntropy cost_fn

2015-05-18 14:38:14,051 INFO:val_init - Generating UniformValGen values of shape (25, 16)
2015-05-18 14:38:14,052 INFO:val_init - Generating UniformValGen values of shape (400, 32)
2015-05-18 14:38:14,053 INFO:val_init - Generating UniformValGen values of shape (500, 512)
2015-05-18 14:38:14,057 INFO:val_init - Generating UniformValGen values of shape (10, 500)
2015-05-18 14:38:14,059 INFO:mnist - loading: train-images-idx3-ubyte
2015-05-18 14:38:14,106 INFO:mnist - loading: train-labels-idx1-ubyte
2015-05-18 14:38:14,108 INFO:mnist - loading: t10k-images-idx3-ubyte
2015-05-18 14:38:14,117 INFO:mnist - loading: t10k-labels-idx1-ubyte
2015-05-18 14:38:14,127 WARNING:dataset - Incompatible batch size. Discarding 16 samples...
2015-05-18 14:38:14,158 WARNING:dataset - Incompatible batch size. Discarding 112 samples...
2015-05-18 14:38:14,176 WARNING:dataset - Incompatible batch size. Discarding 16 samples...
2015-05-18 14:38:14,179 WARNING:dataset - Incompatible batch size. Discarding 112 samples...
2015-05-18 14:38:14,182 INFO:mlp - commencing model fitting
2015-05-18 14:38:14,329 INFO:mlp - epoch: 0, training error: 2.67295
2015-05-18 14:38:14,477 INFO:mlp - epoch: 1, training error: 0.73958
2015-05-18 14:38:14,625 INFO:mlp - epoch: 2, training error: 0.44819
2015-05-18 14:38:14,773 INFO:mlp - epoch: 3, training error: 0.33237
2015-05-18 14:38:14,921 INFO:mlp - epoch: 4, training error: 0.25886
2015-05-18 14:38:14,967 INFO:fit_predict_err - test set MisclassPercentage_TOP_1 3.65585
2015-05-18 14:38:14,995 INFO:fit_predict_err - train set MisclassPercentage_TOP_1 2.30978
```
But when I run the LSTM example by
```
neon -g cudanet mobydick-lstm-small.yaml
```
the issues is
```
2015-05-18 14:41:31,891 DEBUG:cc2 - Copying to GPU
2015-05-18 14:41:31,949 INFO:mlp - Layers:
        DataLayer d0: 128 nodes
        RecurrentLSTMLayer recurrent: 128 inputs, 64 nodes, Tanh act_fn
        RecurrentOutputLayer output: 64 inputs, 128 nodes, Logistic act_fn
        Layer cost: 128 nodes, CrossEntropy cost_fn, utilizing GPU backend


2015-05-18 14:41:31,949 INFO:rnn - DataLayer d0: 128 nodes
2015-05-18 14:41:31,949 INFO:rnn - RecurrentLSTMLayer recurrent: 128 inputs, 64 nodes, Tanh act_fn
2015-05-18 14:41:31,949 INFO:rnn - RecurrentOutputLayer output: 64 inputs, 128 nodes, Logistic act_fn
2015-05-18 14:41:31,949 INFO:rnn - Layer cost: 128 nodes, CrossEntropy cost_fn, utilizing GPU backend

Traceback (most recent call last):
  File "/ocz/gys/NervanaSys/neon/venv/bin/neon", line 240, in <module>
    experiment, result, status = main()
  File "/ocz/gys/NervanaSys/neon/venv/bin/neon", line 208, in main
    result = experiment.run()
  File "/usr/local/lib/python2.7/dist-packages/neon/experiments/fit_predict_err.py", line 98, in run
    super(FitPredictErrorExperiment, self).run()
  File "/usr/local/lib/python2.7/dist-packages/neon/experiments/fit.py", line 101, in run
    self.model.fit(self.dataset)
  File "/usr/local/lib/python2.7/dist-packages/neon/models/rnn.py", line 117, in fit
    self.grad_checker(numgrad="output")
  File "/usr/local/lib/python2.7/dist-packages/neon/models/rnn.py", line 369, in grad_checker
    num_target=num_target, num_i=num_i, num_j=num_j)
  File "/usr/local/lib/python2.7/dist-packages/neon/models/rnn.py", line 216, in fprop
    num_target[num_i, num_j] = (numpy_target + eps)
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/cc2.py", line 285, in __setitem__
    raise TooSlowToImplementError("arbitrary "
neon.util.error.TooSlowToImplementError: arbitrary indexing
```
if I run the lstm example on cpu, everything goes well.

**Comment by scttl** [comment]
Hi @shuokay 

Lack of GPU support for RNNs / LSTMs is already known and being tracked in issue #16

**Comment by shuokay** [comment]
@scttl thank you very much. 
Is there a time schedule of GPU support for RNNs/LSTMs ?

**Comment by scttl** [comment]
@shuokay Not as such, but we're starting to look into the changes required.  Supporting this on the cudanet GPU backend requires a different set of changes than what supporting on the nervanagpu GPU backend requires.  As a loose estimate for seeing these changes in master we're probably talking on the order of a couple of weeks if not sooner.

**Comment by scttl** [comment]
We just pushed some fixes for GPU based RNN and LSTM networks to master (see #16).  cudanet/nervanagpu runs of the two example recurrent networks works ok.

**Comment by hjchen2** [comment]
@shuokay I have tried to run the LSTM example, but I have no mobydick dataset.  Please help me, thanks very much.

**Comment by scttl** [comment]
@hjchen2 it should get downloaded automatically but it's possible project gutenburg is preventing direct linking.  The file in question is available from: http://www.gutenberg.org/cache/epub/2701/pg2701.txt  Simply copy this file to a new directory named `MOBYDICK` inside of wherever your `repo_path` points (which is `~/data` by default).

**Comment by hjchen2** [comment]
@scttl that's great. Thanks a lot.
