### ISSUE TITLE
ImportError: cannot import name __version__ in NeonArgparser

### ISSUE THREAD

**Issue by robi56** [NervanaSystems/neon#321]
I just install neon using this 

```
git clone https://github.com/NervanaSystems/neon.git
cd neon && make sysinstall

```

and  i import 

`from neon.util.argparser import NeonArgparser`
But it gives the follwing error message 

```
Traceback (most recent call last):
      File "./model.py", line 29, in <module>
        from neon.util.argparser import NeonArgparser
      File "/usr/local/lib/python2.7/dist-packages/neon/util/argparser.py", line 31, in <module>
        from neon import __version__ as neon_version
    ImportError: cannot import name __version__
```

**Comment by jennifermyers** [comment]
Hi @robi56,

In neon 1.6. `make sysinstall` calls `python setup.py install` which generates `neon/version.py`.

Can you check whether `neon/version.py` was generated and if not, run `python setup.py install`?

Thanks,
Jennifer
