### ISSUE TITLE
Can't Run Examples

### ISSUE THREAD

**Issue by TomAshley303** [NervanaSystems/neon#322]
I'm not sure what to do now. I've got py2 and 3 installed. I'm using venv and I compiled neon for py3. I have all deps installed (Blas,Cuda.etc) and my GPU is a Titan X Pascal. I activated the python3 env and here's what happened when I ran the first example...

```
(.venv3) user@Computer:~/Code/neon/examples$ python mnist_mlp.py
Traceback (most recent call last):
  File "mnist_mlp.py", line 59, in <module>
    args = parser.parse_args()
  File "/home/user/Code/neon/neon/util/argparser.py", line 353, in parse_args
    compat_mode=args.compat_mode)
  File "/home/user/Code/neon/neon/backends/__init__.py", line 108, in gen_backend
    deterministic=deterministic)
  File "/home/user/Code/neon/neon/backends/backend.py", line 468, in allocate_backend
    return Backend.backends[name](**kargs)
  File "/home/user/Code/neon/neon/backends/nervanagpu.py", line 752, in __init__
    deterministic=deterministic)
  File "/home/user/Code/neon/neon/backends/backend.py", line 480, in __init__
    self.rng = self.gen_rng(rng_seed)
  File "/home/user/Code/neon/neon/backends/nervanagpu.py", line 890, in gen_rng
    self.pcg = rng_mrg()
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/curandom.py", line 788, in __init__
    mrg32k3a_skip_ahead_sequence_source+random_skip_ahead64_source)
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/curandom.py", line 605, in __init__
    state_type, vector_type, generator_bits, additional_source)
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/curandom.py", line 440, in __init__
    self.module = module = pycuda.compiler.SourceModule(source, no_extern_c=True)
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/compiler.py", line 265, in __init__
    arch, code, cache_dir, include_dirs)
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/compiler.py", line 255, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/compiler.py", line 78, in compile_plain
    checksum.update(preprocess_source(source, options, nvcc).encode("utf-8"))
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/compiler.py", line 55, in preprocess_source
    cmdline, stderr=stderr)
pycuda.driver.CompileError: nvcc preprocessing of /tmp/tmprbwo5d0k.cu failed
[command: nvcc --preprocess -arch sm_61 -I/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/cuda /tmp/tmprbwo5d0k.cu --compiler-options -P]
[stderr:
b'In file included from /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime.h:78:0,\n                 from <command-line>:0:\n/usr/local/cuda/bin/../targets/x86_64-linux/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!\n #error -- unsupported GNU version! gcc versions later than 5 are not supported!\n  ^~~~~\n']
(.venv3) user@Computer:~/Code/neon/examples$ gcc --version
gcc (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(.venv3) user@Computer:~/Code/neon/examples$ python mnist_mlp.py
Traceback (most recent call last):
  File "mnist_mlp.py", line 59, in <module>
    args = parser.parse_args()
  File "/home/user/Code/neon/neon/util/argparser.py", line 353, in parse_args
    compat_mode=args.compat_mode)
  File "/home/user/Code/neon/neon/backends/__init__.py", line 108, in gen_backend
    deterministic=deterministic)
  File "/home/user/Code/neon/neon/backends/backend.py", line 468, in allocate_backend
    return Backend.backends[name](**kargs)
  File "/home/user/Code/neon/neon/backends/nervanagpu.py", line 752, in __init__
    deterministic=deterministic)
  File "/home/user/Code/neon/neon/backends/backend.py", line 480, in __init__
    self.rng = self.gen_rng(rng_seed)
  File "/home/user/Code/neon/neon/backends/nervanagpu.py", line 890, in gen_rng
    self.pcg = rng_mrg()
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/curandom.py", line 788, in __init__
    mrg32k3a_skip_ahead_sequence_source+random_skip_ahead64_source)
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/curandom.py", line 605, in __init__
    state_type, vector_type, generator_bits, additional_source)
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/curandom.py", line 440, in __init__
    self.module = module = pycuda.compiler.SourceModule(source, no_extern_c=True)
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/compiler.py", line 265, in __init__
    arch, code, cache_dir, include_dirs)
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/compiler.py", line 255, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/compiler.py", line 78, in compile_plain
    checksum.update(preprocess_source(source, options, nvcc).encode("utf-8"))
  File "/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/compiler.py", line 55, in preprocess_source
    cmdline, stderr=stderr)
pycuda.driver.CompileError: nvcc preprocessing of /tmp/tmp_3okvnbj.cu failed
[command: nvcc --preprocess -arch sm_61 -I/home/user/Code/neon/.venv3/lib/python3.5/site-packages/pycuda/cuda /tmp/tmp_3okvnbj.cu --compiler-options -P]
[stderr:
b'In file included from /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime.h:78:0,\n                 from <command-line>:0:\n/usr/local/cuda/bin/../targets/x86_64-linux/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!\n #error -- unsupported GNU version! gcc versions later than 5 are not supported!\n  ^~~~~\n']
(.venv3) user@Computer:~/Code/neon/examples$
```

**Comment by thestew42** [comment]
I've never encountered this error myself, but it looks like the CUDA compiler does not support your version of GCC. You should be able to install a supported version of GCC (version 5) along with whatever version you have installed.

To get the CUDA compiler to use the older version, you can try using this solution: http://stackoverflow.com/questions/6622454/cuda-incompatible-with-my-gcc-version

**Comment by TomAshley303** [comment]
Great, that fixed it. Just had to install gcc-4.9 package, 'sudo ln -s /usr/bin/gcc-4.9 /usr/local/cuda/bin/gcc' then install g++4.9 package and now training super fast on my Titan! Thanks.
