### ISSUE TITLE
ArrayIterator Error when make_onehot is false

### ISSUE THREAD

**Issue by koglp** [NervanaSystems/neon#330]
I implemented some codes to test a regression issue on Neon.
An error occurred at ArrayIterator when the value of make_onehot is false. 
So I attached a problematic code and error logs.
The following code is the same as you provided.
(http://neon.nervanasys.com/index.html/generated/neon.data.dataiterator.ArrayIterator.html)

code : test.py
`from neon.data import ArrayIterator`
`import numpy as np`
`X = np.random.rand(1000, 1)`
`y = 2*X + 1 + 0.01*np.random.randn(1000, 1)  # y = 2X+1 with some gaussian noise`
`train = ArrayIterator(X=X, y=y, make_onehot=False)`

error logs
$~/example/# python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from neon.data import ArrayIterator
  File "/usr/local/lib/python2.7/dist-packages/neon-1.7.0-py2.7.egg/neon/data/__init__.py", line 27, in <module>
    from neon.data.image import MNIST, CIFAR10
  File "/usr/local/lib/python2.7/dist-packages/neon-1.7.0-py2.7.egg/neon/data/image.py", line 20, in <module>
    standard_library.install_aliases()  # triggers E402, hence noqa below
  File "/usr/local/lib/python2.7/dist-packages/future/standard_library/__init__.py", line 483, in install_aliases
    import test
  File ".../example/test.py", line 14, in <module>
    train = ArrayIterator(X=X, y=y, make_onehot=False)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.7.0-py2.7.egg/neon/data/dataiterator.py", line 109, in __init__
    assert self.ndata >= self.be.bsz

**Comment by nervetumer** [comment]
I am unable to replicate this error.  Some code must be missing because you need to generate a backend first.  But the error you printed is not the error that occurs if a backend is not there.  I ran this code below and got no error:
```
from neon.backends import gen_backend
be=gen_backend(backend='gpu', batch_size=32)
from neon.data import ArrayIterator
import numpy as np
X = np.random.rand(1000, 1)
y = 2*X + 1 + 0.01*np.random.randn(1000, 1) # y = 2X+1 with some gaussian noise
train = ArrayIterator(X=X, y=y, make_onehot=False)
```

as well as 
```
from neon.backends import gen_backend
be=gen_backend(backend='cpu')#, batch_size=32)
from neon.data import ArrayIterator
import numpy as np
X = np.random.rand(1000, 1)
y = 2*X + 1 + 0.01*np.random.randn(1000, 1) # y = 2X+1 with some gaussian noise
train = ArrayIterator(X=X, y=y, make_onehot=False)
```

**Comment by koglp** [comment]
@nervetumer, thank for reply. But, I got another error after I added the 'be = gen_backend('gpu')'.

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from neon.data import ArrayIterator
  File "/usr/local/lib/python2.7/dist-packages/neon-1.7.0-py2.7.egg/neon/data/__init__.py", line 18, in <module>
    from neon.data.datasets import Dataset
  File "/usr/local/lib/python2.7/dist-packages/neon-1.7.0-py2.7.egg/neon/data/datasets.py", line 20, in <module>
    standard_library.install_aliases()  # triggers E402, hence noqa below
  File "/usr/local/lib/python2.7/dist-packages/future/standard_library/__init__.py", line 483, in install_aliases
    import test
  File "/root/example/test.py", line 7, in <module>
    train = ArrayIterator(X=X, y=y, make_onehot=False)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.7.0-py2.7.egg/neon/data/dataiterator.py", line 152, in __init__
    self.Xdev, self.Xbuf, self.unpack_func = list(zip(*[transpose_gen(x) for x in X]))
  File "/usr/local/lib/python2.7/dist-packages/neon-1.7.0-py2.7.egg/neon/data/dataiterator.py", line 145, in transpose_gen
    return (self.be.array(z), self.be.iobuf(z.shape[1]),
  File "/usr/local/lib/python2.7/dist-packages/neon-1.7.0-py2.7.egg/neon/backends/backend.py", line 588, in iobuf
    out_tsr[:] = 0
  File "/usr/local/lib/python2.7/dist-packages/neon-1.7.0-py2.7.egg/neon/backends/nervanagpu.py", line 190, in __setitem__
    self.__getitem__(index)._assign(value)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.7.0-py2.7.egg/neon/backends/nervanagpu.py", line 357, in _assign
    self.gpudata, unpack_from('I', value)[0], self.size, stream)
Boost.Python.ArgumentError: Python argument types in
    pycuda._driver.memset_d32_async(NoneType, int, int, NoneType)
did not match C++ signature:
    memset_d32_async(unsigned long long dest, unsigned int data, unsigned int size, boost::python::api::object stream=None)

**Comment by nervetumer** [comment]
for GPU you need to set the batch_size as i did in the code i copied above.  please use the exact code i used:
"be=gen_backend(backend='gpu', batch_size=32)"

NOT
be=gen_backend(backend='cpu')

The line without batch_size is for the CPU backend

**Comment by jennifermyers** [comment]
Closing this issue. @koglp let us know if you still have problems after setting batch_size.
