### ISSUE TITLE
shapes not aligned, timeseries_lstm.py

### ISSUE THREAD

**Issue by ghost** [NervanaSystems/neon#337]
I recently downloaded neon source code, and ran few models. Other models worked like charm, but when I ran timeseries_lstm.py, it threw error. It read:

```
C:\Python27\python.exe D:/neon/test/timeseries_lstm.py
C:\Python27\lib\site-packages\skcuda\cublas.py:272: UserWarning: creating CUBLAS context to get version number
  warnings.warn('creating CUBLAS context to get version number')
Traceback (most recent call last):
  File "D:/neon/test/timeseries_lstm.py", line 314, in <module>
    callbacks=callbacks)
  File "D:\neon\models\model.py", line 175, in fit
    self._epoch_fit(dataset, callbacks)
  File "D:\neon\models\model.py", line 197, in _epoch_fit
    x = self.fprop(x)
  File "D:\neon\models\model.py", line 228, in fprop
    return self.layers.fprop(x, inference)
  File "D:\neon\layers\container.py", line 330, in fprop
    x = l.fprop(x, inference=inference)
  File "D:\neon\layers\recurrent.py", line 450, in fprop
    self.be.compound_dot(self.W_recur, h_prev, ifog, beta=1.0)
  File "D:\neon\backends\nervanacpu.py", line 905, in compound_dot
    np.dot(A._tensor, B._tensor, tmp)
ValueError: shapes (128,32) and (32,1,1) not aligned: 32 (dim 1) != 1 (dim 1)

```

I am running Windows 8.1 64bit

**Comment by ursk** [comment]
Neon does not officially support Windows, and this error does not occur under Linux / Mac operating systems.
