### ISSUE TITLE
error when interrupt and resume training!

### ISSUE THREAD

**Issue by andyyuan78** [NervanaSystems/neon#34]
while I am runung 'neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp32.yaml
' on training about 50 hours , I had to restart my computer, when I resume the same command, the error happens, here the log:

ubgpu@ubgpu:~/github/neon/neon$  neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp32.yaml
[sudo] password for ubgpu: 
WARNING:neon.util.persist:deserializing object from:  examples/convnet/i1k-alexnet-fp32.yaml
WARNING:neon.datasets.imageset:Imageset initialized with dtype <type 'numpy.float32'>
2015-05-18 20:44:17,102 WARNING:neon - setting log level to: 20
2015-05-18 20:44:17,233 INFO:gpu - Initialized NervanaGPU with stochastic_round=None
2015-05-18 20:44:17,233 INFO:gpu - Seeding random number generator with: None
2015-05-18 20:44:17,234 INFO:__init__ - NervanaGPU backend, RNG seed: None, numerr: None
2015-05-18 20:44:17,234 INFO:mlp - Layers:
        ImageDataLayer d0: 3 x (224 x 224) nodes
        ConvLayer conv1: 3 x (224 x 224) inputs, 64 x (55 x 55) nodes, RectLin act_fn
        PoolingLayer pool1: 64 x (55 x 55) inputs, 64 x (27 x 27) nodes, Linear act_fn
        ConvLayer conv2: 64 x (27 x 27) inputs, 192 x (27 x 27) nodes, RectLin act_fn
        PoolingLayer pool2: 192 x (27 x 27) inputs, 192 x (13 x 13) nodes, Linear act_fn
        ConvLayer conv3: 192 x (13 x 13) inputs, 384 x (13 x 13) nodes, RectLin act_fn
        ConvLayer conv4: 384 x (13 x 13) inputs, 256 x (13 x 13) nodes, RectLin act_fn
        ConvLayer conv5: 256 x (13 x 13) inputs, 256 x (13 x 13) nodes, RectLin act_fn
        PoolingLayer pool3: 256 x (13 x 13) inputs, 256 x (6 x 6) nodes, Linear act_fn
        FCLayer fc4096a: 9216 inputs, 4096 nodes, RectLin act_fn
        DropOutLayer dropout1: 4096 inputs, 4096 nodes, Linear act_fn
        FCLayer fc4096b: 4096 inputs, 4096 nodes, RectLin act_fn
        DropOutLayer dropout2: 4096 inputs, 4096 nodes, Linear act_fn
        FCLayer fc1000: 4096 inputs, 1000 nodes, Softmax act_fn
        CostLayer cost: 1000 nodes, CrossEntropy cost_fn

2015-05-18 20:44:17,234 INFO:batch_norm - BatchNormalization set to train mode
2015-05-18 20:44:17,236 INFO:val_init - Generating AutoUniformValGen values of shape (363, 64)
2015-05-18 20:44:17,237 INFO:batch_norm - BatchNormalization set to train mode
2015-05-18 20:44:17,238 INFO:val_init - Generating AutoUniformValGen values of shape (1600, 192)
2015-05-18 20:44:17,244 INFO:batch_norm - BatchNormalization set to train mode
2015-05-18 20:44:17,245 INFO:val_init - Generating AutoUniformValGen values of shape (1728, 384)
2015-05-18 20:44:17,255 INFO:batch_norm - BatchNormalization set to train mode
2015-05-18 20:44:17,256 INFO:val_init - Generating AutoUniformValGen values of shape (3456, 256)
2015-05-18 20:44:17,269 INFO:batch_norm - BatchNormalization set to train mode
2015-05-18 20:44:17,270 INFO:val_init - Generating AutoUniformValGen values of shape (2304, 256)
2015-05-18 20:44:17,279 INFO:batch_norm - BatchNormalization set to train mode
2015-05-18 20:44:17,280 INFO:val_init - Generating AutoUniformValGen values of shape (4096, 9216)
2015-05-18 20:44:17,748 INFO:batch_norm - BatchNormalization set to train mode
2015-05-18 20:44:17,749 INFO:val_init - Generating AutoUniformValGen values of shape (4096, 4096)
2015-05-18 20:44:17,959 INFO:val_init - Generating AutoUniformValGen values of shape (1000, 4096)
2015-05-18 20:44:18,016 INFO:fit - Unable to find saved model /home/ubgpu/data/I1K/I1K_alexnet_fp32_model.prm, starting over
2015-05-18 20:44:18,017 INFO:mlp - commencing model fitting
Traceback (most recent call last):
  File "/usr/local/bin/neon", line 199, in <module>
    experiment, result, status = main()
  File "/usr/local/bin/neon", line 168, in main
    result = experiment.run()
  File "/usr/local/lib/python2.7/dist-packages/neon/experiments/fit_predict_err.py", line 97, in run
    super(FitPredictErrorExperiment, self).run()
  File "/usr/local/lib/python2.7/dist-packages/neon/experiments/fit.py", line 99, in run
    self.model.fit(self.dataset)
  File "/usr/local/lib/python2.7/dist-packages/neon/models/mlp.py", line 141, in fit
    self.fprop()
  File "/usr/local/lib/python2.7/dist-packages/neon/models/mlp.py", line 81, in fprop
    ll.fprop(y)
  File "/usr/local/lib/python2.7/dist-packages/neon/layers/layer.py", line 373, in fprop
    self.batch_idx)
  File "/usr/local/lib/python2.7/dist-packages/neon/datasets/imageset.py", line 314, in get_mini_batch
    self.backend.subtract(self.inp_be, self.mean_be, self.inp_be)
  File "/usr/local/lib/python2.7/dist-packages/neon/backends/gpu.py", line 643, in subtract
    self.ng.subtract(left, right, out=out)
  File "/usr/local/lib/python2.7/dist-packages/nervanagpu/nervanagpu.py", line 801, in subtract
    def subtract    (self, a, b, out=None): return OpTreeNode.build("sub", a, b, out=out)
  File "/usr/local/lib/python2.7/dist-packages/nervanagpu/nervanagpu.py", line 915, in build
    return OpTreeNode({ "op" : "assign" }, out, node).execute()
  File "/usr/local/lib/python2.7/dist-packages/nervanagpu/nervanagpu.py", line 924, in execute
    return call_compound_kernel(_get_rand_state(), *stack)
  File "/usr/local/lib/python2.7/dist-packages/nervanagpu/float_ew.py", line 835, in call_compound_kernel
    kernel = _get_compound_kernel(tuple(type_args))
  File "<string>", line 2, in _get_compound_kernel
  File "/usr/local/lib/python2.7/dist-packages/pycuda/tools.py", line 423, in context_dependent_memoize
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/nervanagpu/float_ew.py", line 670, in _get_compound_kernel
    module = _get_module(template, template_vals)
  File "/usr/local/lib/python2.7/dist-packages/nervanagpu/float_ew.py", line 313, in _get_module
    return SourceModule(code, options=["--use_fast_math" ], keep=False) #,"-G"
  File "/usr/local/lib/python2.7/dist-packages/pycuda/compiler.py", line 251, in __init__
    arch, code, cache_dir, include_dirs)
  File "/usr/local/lib/python2.7/dist-packages/pycuda/compiler.py", line 241, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir)
  File "/usr/local/lib/python2.7/dist-packages/pycuda/compiler.py", line 73, in compile_plain
    checksum.update(preprocess_source(source, options, nvcc).encode("utf-8"))
  File "/usr/local/lib/python2.7/dist-packages/pycuda/compiler.py", line 47, in preprocess_source
    result, stdout, stderr = call_capture_output(cmdline, error_on_nonzero=False)
  File "/usr/local/lib/python2.7/dist-packages/pytools/prefork.py", line 197, in call_capture_output
    return forker[0].call_capture_output(cmdline, cwd, error_on_nonzero)
  File "/usr/local/lib/python2.7/dist-packages/pytools/prefork.py", line 54, in call_capture_output
    % ( " ".join(cmdline), e))
pytools.prefork.ExecError: error invoking 'nvcc --preprocess --use_fast_math -arch sm_52 -I/usr/local/lib/python2.7/dist-packages/pycuda/cuda /tmp/tmpltSwQ9.cu --compiler-options -P': [Errno 2] No such file or directory

**Comment by apark263** [comment]
seems like nvcc is not in your path.

Try adding the cuda bin dir that has nvcc to your user path and not running
as sudo, or export the path variable when you run as sudo.

**Comment by CAWEHbKA** [comment]
There is also another problem. It is in line:
2015-05-18 20:44:18,016 INFO:fit - Unable to find saved model /home/ubgpu/data/I1K/I1K_alexnet_fp32_model.prm, starting over

All the previous execution was not saved. If you fix you cuda problem, you still will not be able to continue the previous execution...
Somebody knows how to configure neon to save snapshots?

**Comment by apark263** [comment]
Snapshotting as a feature is a work in progress.  It's easy enough to do in
the fit function of mlp.py by calling serialize(self.get_params(),
self.serialized_path), but for yaml exposure we're trying to decide on a
way that isn't confusing to the user.

For now you can just save out incrementally and extend the number of epochs
each time.  (i.e. use num_epochs: 10, save out, then extend to 20, etc._

**Comment by scttl** [comment]
The incremental save and epoch extend approach that is currently implemented is described in a bit more detail here: http://neon.nervanasys.com/docs/latest/experiments.html?highlight=saving#generating-predictions

**Comment by apark263** [comment]
Serialization on a schedule for snapshotting has now been added

**Comment by andyyuan78** [comment]
yes, not sure something delete my /usr/localcuda/bin
no it is OK
