### ISSUE TITLE
Add multiple Misclassification doesn't work.

### ISSUE THREAD

**Issue by mingwugmail** [NervanaSystems/neon#353]
I added

examples/cifar10_msra/train.py, line 54

callbacks.add_callback(MetricCallback(test, TopKMisclassification(3)))
callbacks.add_callback(MetricCallback(test, TopKMisclassification(5)))
callbacks.add_callback(MetricCallback(test, TopKMisclassification(10)))

then:
$ python train.py    --backend cpu     --no_progress_bar         --depth 111         --save_path save

it errors out:

Traceback (most recent call last):
  File "train.py", line 61, in <module>
    model.fit(train, optimizer=opt, num_epochs=args.epochs, cost=cost, callbacks=callbacks)
  File "/home/zhou/project/neon-1.8.1/neon/models/model.py", line 176, in fit
    callbacks.on_train_begin(num_epochs)
  File "/home/zhou/project/neon-1.8.1/neon/callbacks/callbacks.py", line 268, in on_train_begin
    c.on_train_begin(self.callback_data, self.model(), epochs)
  File "/home/zhou/project/neon-1.8.1/neon/callbacks/callbacks.py", line 849, in on_train_begin
    callback_data.create_dataset(group_name, (epochs // self.epoch_freq,))
  File "/home/zhou/project/neon-1.8.1/.venv2/local/lib/python2.7/site-packages/h5py/_hl/group.py", line 108, in create_dataset
    self[name] = dset
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
  File "/home/zhou/project/neon-1.8.1/.venv2/local/lib/python2.7/site-packages/h5py/_hl/group.py", line 277, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link (/tmp/pip-4rPeHA-build/h5py/h5o.c:3731)
RuntimeError: Unable to create link (Name already exists)

It's just a Metric Callback, ideally the user should be able to add as much as s/he likes, hence I think this is a bug.

**Comment by hanlin-nervana** [comment]
That's correct, we support multiple Metric Callbacks being added, but not multiple metric callbacks with the same `metric_name`. (we use the `metric_name` to create the hdf5 dataset where we store the results). Each `TopKMisclassification` metric adds duplicate metric names such as `LogLoss`, causing the error you report.

A workaround for now is to modify the offending line to check if the group_name already exists before attempting to create a new dataset in `callback_data`.
