### ISSUE TITLE
System-wide installation returns "ImportError: No module named builtins"

### ISSUE THREAD

**Issue by omar-florez** [NervanaSystems/neon#372]
Following installation instructions from http://neon.nervanasys.com/docs/latest/installation.html:

- git clone https://github.com/NervanaSystems/neon.git
- cd neon && make sysinstall

leads to the following error when calling neon layers. This is because folder _builtins_ is not available in current codebase (neon-1.8.2). Installation based on virtual environment works correctly.

```
Traceback (most recent call last):
  File "/usr/local/bin/neon", line 4, in <module>
    __import__('pkg_resources').run_script('neon==1.8.2', 'neon')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/neon-1.8.2-py2.7.egg/EGG-INFO/scripts/neon", line 48, in <module>
    from neon import logger
  File "/usr/local/lib/python2.7/site-packages/neon-1.8.2-py2.7.egg/neon/__init__.py", line 19, in <module>
    from builtins import zip
```

**Comment by wei-v-wang** [comment]
We believe this issue is addressed in recent neon releases. Could you please try again? 

Thank you!

**Comment by wei-v-wang** [comment]
Please re-open if "latest" still has the same issue.
