### ISSUE TITLE
duplicate dir name in examples/cifar10_msra/data.py

### ISSUE THREAD

**Issue by chengchingwen** [NervanaSystems/neon#379]
I followed the neon course tutorial 02 and came across this error in `examples/cifar10_msra/data.py`. Apparently, the image path was duplicated with the `out_dir` in it.

```
Traceback (most recent call last):
  File "examples/cifar10_msra/data.py", line 132, in <module>
    generated_files = ingest_cifar10(args.out_dir, args.padded_size)
  File "examples/cifar10_msra/data.py", line 67, in ingest_cifar10
    im.save(os.path.join(out_dir, img_path), format='PNG')
  File "/Users/chengchingwen/Desktop/gitrep/neon/.venv3/lib/python3.6/site-packages/PIL/Image.py", line 1682, in save
    fp = builtins.open(filename, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/cifar10/data/cifar10/train/6/0.png'
(.venv3) zhengjiwendeMBP:neon chengchingwen$ python examples/cifar10_msra/data.py --out_dir data/cifar10/
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "examples/cifar10_msra/data.py", line 132, in <module>
    generated_files = ingest_cifar10(args.out_dir, args.padded_size)
  File "examples/cifar10_msra/data.py", line 67, in ingest_cifar10
    im.save(os.path.join(out_dir, img_path), format='PNG')
  File "/Users/chengchingwen/Desktop/gitrep/neon/.venv3/lib/python3.6/site-packages/PIL/Image.py", line 1682, in save
    fp = builtins.open(filename, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/cifar10/data/cifar10/train/6/0.png'
```

**Comment by wei-v-wang** [comment]
Errors in cifar10_msra like above disappeared with neon 2.2. Please verify. Thanks, @chengchingwen !

**Comment by wei-v-wang** [comment]
Please re-open if errors occur in latest neon. https://github.com/NervanaSystems/neon/tree/latest
