### ISSUE TITLE
ArrayIterator and 3D numpy array

### ISSUE THREAD

**Issue by elena-orlova** [NervanaSystems/neon#384]
Hello! 

We are working on GAN for particle simulation. Firstly, I want to understand how the model works in a simple case, so I created my own dataset as numpy arrays, "images" 25 x 25 x 25 and some labels (0 or 1). In fact, our dataset for further work is a big set of 25*25*25 images.
But I faced with some problems: there are some errors when I use ArrayIterator. My code https://github.com/elena-orlova/CERN-Project/blob/master/gan3D.py 
Data generation: https://github.com/elena-orlova/CERN-Project/blob/master/gen_data.py
Error message: 

>Traceback (most recent call last):
  File "gan3D.py", line 26, in <module>
    train_set = ArrayIterator(X=train_data, y=data_y)
  File "//anaconda/envs/neon/lib/python3.6/site-packages/neon-2.0.0-py3.6.egg/neon/data/dataiterator.py", line 109, in __init__
    assert self.ndata >= self.be.bsz
AttributeError: 'NoneType' object has no attribute 'bsz'

As I see ArrayIterator works with numpy arrays, so what could cause the problem? 

Thanks in advance!

**Comment by elena-orlova** [comment]
I've found the solution
https://github.com/NervanaSystems/neon/issues/142

Thank you anyway!
