### ISSUE TITLE
Simple Example mnist-small doesn't work

### ISSUE THREAD

**Issue by Tgaaly** [NervanaSystems/neon#41]
I installed neon on my Macbook (no gpu) and tried the simple mnist-small.yaml example and got the following error trace. This is my first time using Neon!

WARNING:neon.util.persist:deserializing object from:  examples/mlp/mnist-small.yaml
2015-05-26 21:04:47,289 WARNING:neon - setting log level to: 20
2015-05-26 21:04:47,290 INFO:cpu - Seeding random number generator with: None
2015-05-26 21:04:47,298 INFO:__init__ - CPU backend, RNG seed: None, numerr: None
2015-05-26 21:04:47,298 INFO:mlp - Layers:
	DataLayer d0: 784 nodes
	FCLayer h0: 784 inputs, 100 nodes, RectLin act_fn
	FCLayer output: 100 inputs, 10 nodes, Logistic act_fn
	CostLayer cost: 10 nodes, CrossEntropy cost_fn

2015-05-26 21:04:47,299 INFO:val_init - Generating GaussianValGen values of shape (100, 784)
2015-05-26 21:04:47,305 INFO:val_init - Generating GaussianValGen values of shape (10, 100)
2015-05-26 21:04:47,307 INFO:mnist - loading: train-images-idx3-ubyte
2015-05-26 21:04:47,667 INFO:mnist - loading: train-labels-idx1-ubyte
2015-05-26 21:04:47,675 INFO:mnist - loading: t10k-images-idx3-ubyte
2015-05-26 21:04:47,710 INFO:mnist - loading: t10k-labels-idx1-ubyte
2015-05-26 21:04:47,711 WARNING:dataset - Incompatible batch size. Discarding 16 samples...
2015-05-26 21:04:47,764 WARNING:dataset - Incompatible batch size. Discarding 96 samples...
2015-05-26 21:04:48,146 WARNING:dataset - Incompatible batch size. Discarding 16 samples...
2015-05-26 21:04:48,148 WARNING:dataset - Incompatible batch size. Discarding 96 samples...
2015-05-26 21:04:48,155 INFO:mlp - commencing model fitting
Traceback (most recent call last):
  File "/usr/local/bin/neon", line 240, in <module>
    experiment, result, status = main()
  File "/usr/local/bin/neon", line 208, in main
    result = experiment.run()
  File "/Library/Python/2.7/site-packages/neon/experiments/fit_predict_err.py", line 99, in run
    super(FitPredictErrorExperiment, self).run()
  File "/Library/Python/2.7/site-packages/neon/experiments/fit.py", line 102, in run
    self.model.fit(self.dataset)
  File "/Library/Python/2.7/site-packages/neon/models/mlp.py", line 156, in fit
    self.backend.add(error, self.cost_layer.get_cost(), error)
  File "/Library/Python/2.7/site-packages/neon/layers/layer.py", line 289, in get_cost
    scale_by_batchsize=scale_cost)
  File "/Library/Python/2.7/site-packages/neon/transforms/cross_entropy.py", line 237, in apply_function
    scale_by_batchsize=scale_by_batchsize)
  File "/Library/Python/2.7/site-packages/neon/transforms/cross_entropy.py", line 62, in cross_entropy
    return backend.sum(temp[0], axes=None, out=result)
  File "/Library/Python/2.7/site-packages/neon/backends/cpu.py", line 764, in sum
    np.sum(tsr._tensor, axis=axes, out=out._tensor, keepdims=True)
TypeError: sum() got an unexpected keyword argument 'keepdims'

**Comment by fchollet** [comment]
It is possible that you are using an older version of Numpy where the `sum` function did not yet support the argument `keepdims`... Reinstalling Numpy from pip should likely solve your problem.

**Comment by Tgaaly** [comment]
my numpy is update. but i reinstalled it in anycase and this didnt fix anything.

**Comment by ursk** [comment]
Hi,

we actually require numpy 1.8.1.

**Comment by Tgaaly** [comment]
my bad. reinstalled everything and it worked.
