### ISSUE TITLE
libmklml_intel.so not found 

### ISSUE THREAD

**Issue by yiqiaoc11** [NervanaSystems/neon#445]
This one has similar symptom as #438. Running bAbI @ Anaconda 3.5 with latest version. 

Traceback (most recent call last):
  File "examples/babi/train.py", line 81, in <module>
    be = gen_backend(**extract_valid_args(args, gen_backend))
  File "/home/watson/anaconda3/lib/python3.6/site-packages/neon/backends/__init__.py", line 113, in
gen_backend
    deterministic=deterministic)
  File "/home/watson/anaconda3/lib/python3.6/site-packages/neon/backends/backend.py", line 468, in a
llocate_backend
    return Backend.backends[name](**kargs)
  File "/home/watson/anaconda3/lib/python3.6/site-packages/neon/backends/nervanamkl.py", line 213, i
n __init__
    self.mklEngine = ctypes.cdll.LoadLibrary(mkl_engine_path)
  File "/home/watson/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/home/watson/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmklml_gnu.so: cannot open shared object file: No such file or directory

**Comment by yiqiaoc11** [comment]
ctypes.cdll.LoadLibrary(mkl_engine_path), mkl_engine_path is correct, but can't be loaded.

**Comment by wei-v-wang** [comment]
Can you paste your "echo $LD_LIBRARY_PATH" and see if that path contains libmklml_gnu.so?

**Comment by yiqiaoc11** [comment]
:/usr/local/lib
I just got this one resolved by reinstalling it with conda rather than pip. We can close this one. 
BTW, the installation tutorial indicates we need to create source activation for neon. Not sure if we can ignore it as we might need include some pytorch packages which could conflict with activated neon.

**Comment by Pratyusha1796** [comment]
@yiqiaoc11  can you help me out with this same error i am facing
2018-03-10 12:13:24,836 - neon.backends - WARNING - deterministic_update and deterministic args are deprecated in favor of specifying random seed
Traceback (most recent call last):
  File "inference.py", line 57, in <module>
    be = gen_backend(**extract_valid_args(args, gen_backend))
  File "/home/pratyusha/Envs/ronin/local/lib/python2.7/site-packages/neon/backends/__init__.py", line 113, in gen_backend
    deterministic=deterministic)
  File "/home/pratyusha/Envs/ronin/local/lib/python2.7/site-packages/neon/backends/backend.py", line 468, in allocate_backend
    return Backend.backends[name](**kargs)
  File "/home/pratyusha/Envs/ronin/local/lib/python2.7/site-packages/neon/backends/nervanamkl.py", line 213, in __init__
    self.mklEngine = ctypes.cdll.LoadLibrary(mkl_engine_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmklml_gnu.so: cannot open shared object file: No such file or directory

**Comment by wei-v-wang** [comment]
As a workaround, can you download neon and do "make clean; make" , i.e. not using pip for now.
