### ISSUE TITLE
cannot run "neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp32.yaml" 

### ISSUE THREAD

**Issue by zhengdong914** [NervanaSystems/neon#50]
i've installed nervanagpu sucessfully,when i run "neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp32.yaml"  mistakes happens as below:
dsp@dsp:~/neon$ neon --gpu nervanagpu examples/convnet/i1k-alexnet-fp32.yaml
WARNING:neon.util.persist:deserializing object from:  examples/convnet/i1k-alexnet-fp32.yaml
WARNING:neon.datasets.imageset:Imageset initialized with dtype <type 'numpy.float32'>
2015-06-15 22:35:55,300 WARNING:neon - setting log level to: 20
2015-06-15 22:35:55,385 INFO:gpu - Initialized NervanaGPU with stochastic_round=None
2015-06-15 22:35:55,385 INFO:gpu - Seeding random number generator with: None
2015-06-15 22:35:55,386 INFO:__init__ - NervanaGPU backend, RNG seed: None, numerr: None
2015-06-15 22:35:55,386 INFO:mlp - Layers:
	ImageDataLayer d0: 3 x (224 x 224) nodes
	ConvLayer conv1: 3 x (224 x 224) inputs, 64 x (55 x 55) nodes, RectLin act_fn
	PoolingLayer pool1: 64 x (55 x 55) inputs, 64 x (27 x 27) nodes, Linear act_fn
	ConvLayer conv2: 64 x (27 x 27) inputs, 192 x (27 x 27) nodes, RectLin act_fn
	PoolingLayer pool2: 192 x (27 x 27) inputs, 192 x (13 x 13) nodes, Linear act_fn
	ConvLayer conv3: 192 x (13 x 13) inputs, 384 x (13 x 13) nodes, RectLin act_fn
	ConvLayer conv4: 384 x (13 x 13) inputs, 256 x (13 x 13) nodes, RectLin act_fn
	ConvLayer conv5: 256 x (13 x 13) inputs, 256 x (13 x 13) nodes, RectLin act_fn
	PoolingLayer pool3: 256 x (13 x 13) inputs, 256 x (6 x 6) nodes, Linear act_fn
	FCLayer fc4096a: 9216 inputs, 4096 nodes, RectLin act_fn
	DropOutLayer dropout1: 4096 inputs, 4096 nodes, Linear act_fn
	FCLayer fc4096b: 4096 inputs, 4096 nodes, RectLin act_fn
	DropOutLayer dropout2: 4096 inputs, 4096 nodes, Linear act_fn
	FCLayer fc1000: 4096 inputs, 1000 nodes, Softmax act_fn
	CostLayer cost: 1000 nodes, CrossEntropy cost_fn

2015-06-15 22:35:55,386 INFO:batch_norm - BatchNormalization set to train mode
Traceback (most recent call last):
  File "/home/dsp/anaconda/bin/neon", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/dsp/neon/bin/neon", line 240, in <module>
    experiment, result, status = main()
  File "/home/dsp/neon/bin/neon", line 207, in main
    experiment.initialize(backend)
  File "/home/dsp/neon/neon/experiments/fit_predict_err.py", line 62, in initialize
    super(FitPredictErrorExperiment, self).initialize(backend)
  File "/home/dsp/neon/neon/experiments/fit.py", line 62, in initialize
    self.model.initialize(backend)
  File "/home/dsp/neon/neon/models/mlp.py", line 61, in initialize
    ll.initialize(kwargs)
  File "/home/dsp/neon/neon/layers/convolutional.py", line 39, in initialize
    super(ConvLayer, self).initialize(kwargs)
  File "/home/dsp/neon/neon/layers/layer.py", line 479, in initialize
    self.bn.initialize(kwargs)
  File "/home/dsp/neon/neon/transforms/batch_norm.py", line 90, in initialize
    self._xhat = self.backend.zeros(self.in_shape, dtype=self.dtype)
  File "/home/dsp/neon/neon/backends/gpu.py", line 582, in zeros
    return self.ng.zeros(shape, dtype=dtype)
  File "/home/dsp/anaconda/lib/python2.7/site-packages/nervanagpu/nervanagpu.py", line 483, in zeros
    name=name, rounding=self.round_mode)._assign(0)
  File "/home/dsp/anaconda/lib/python2.7/site-packages/nervanagpu/nervanagpu.py", line 298, in _assign
    drv.memset_d32_async(self.gpudata,
AttributeError: 'module' object has no attribute 'memset_d32_async'

**Comment by apark263** [comment]
Please install the latest pycuda from github or from the pycuda website.
The pypi distribution is out of date.

https://github.com/inducer/pycuda

**Comment by zhengdong914** [comment]
@apark263 thank you! it works!!
