### ISSUE TITLE
Could I use branch "MGPUDev"?

### ISSUE THREAD

**Issue by Jokeren** [NervanaSystems/neon#53]
I tried to checkout this branch, and run the example/convnet/mnist-small.yaml. But there are even indentation errors in the file:

WARNING:neon.util.persist:deserializing object from:  mnist-small.yaml
2015-06-26 11:26:21,774 WARNING:neon - setting log level to: 20
Traceback (most recent call last):
  File "/home/zxx/Install/python2.7.9/bin/neon", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/zxx/neon_dev/bin/neon", line 236, in <module>
    experiment, result, status = main()
  File "/home/zxx/neon_dev/bin/neon", line 198, in main
    device_id=args.device_id)
  File "/home/zxx/neon_dev/neon/backends/__init__.py", line 98, in gen_backend
    from neon.backends.cc2 import GPU
  File "/home/zxx/neon_dev/neon/backends/cc2.py", line 1367
    def update_fc_bias(self, err, out):
                                      ^
**IndentationError: unindent does not match any outer indentation level**

Does that indicate the *master* is the only stable branch we could use?

**Comment by apark263** [comment]
This is an experimental branch whose github version doesn't work yet. The
working one is Maxwell only and will be merged in to the next release of
neon.
