### ISSUE TITLE
IOError: when writing train batches of  imagenet  

### ISSUE THREAD

**Issue by xiuxiazhang** [NervanaSystems/neon#68]
Hello, 
 I am  trying to run   i1k-alexnet-fp32.yaml example, and  I have data ready in this directory 

[zxx@ga85 neon_dev]$ ls /mnt/bak_store01/zxx/imagenet/data/I1K/
ILSVRC2012_devkit_t12.tar.gz  ILSVRC2012_img_train.tar  ILSVRC2012_img_val.tar  imageset_batches

and modified  two lines of examples/convnet/i1k-alexnet-fp32.yaml file

47   dataset: &ds !obj:datasets.Imageset {
 48     repo_path: '/mnt/bak_store01/zxx/imagenet/data/',
 49     imageset: 'I1K',
 50     square_crop: True,
 51     save_dir: '/mnt/bak_store01/zxx/imagenet/data/I1K/imageset_batches',

However, when I am trying to generate imageset batches, it has the IO errors. 
My current neon's version is v0.8.2, since I only have kepler GPU.

[zxx@ga85 neon_dev]$ neon --gpu cudanet examples/convnet/i1k-alexnet-fp32.yaml 
2015-08-10 02:05:01,401 INFO:batch_writer - 90% ...
2015-08-10 02:05:20,666 INFO:batch_writer - created list of jpg files
2015-08-10 02:05:20,666 INFO:batch_writer - Number of training files = 1281167
2015-08-10 02:05:22,446 INFO:batch_writer - Writing train batches...
Traceback (most recent call last):
  File "/home/zxx/Install/python2.7.10/bin/neon", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/zxx/neon_dev/bin/neon", line 240, in <module>
    experiment, result, status = main()
  File "/home/zxx/neon_dev/bin/neon", line 208, in main
    result = experiment.run()
  File "/home/zxx/neon_dev/neon/experiments/fit_predict_err.py", line 99, in run
    super(FitPredictErrorExperiment, self).run()
  File "/home/zxx/neon_dev/neon/experiments/fit.py", line 73, in run
    self.dataset.load(backend=self.backend, experiment=self)
  File "/home/zxx/neon_dev/neon/datasets/imageset.py", line 178, in load
    self.bw.run()
  File "/home/zxx/neon_dev/neon/util/batch_writer.py", line 293, in run
    t_jpegfiles, targets=None, is_tar=True)
  File "/home/zxx/neon_dev/neon/util/batch_writer.py", line 177, in write_batches
    functools.partial(proc_img, is_string=is_tar), jpeg_file_batch)
  File "/home/zxx/Install/python2.7.10/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/zxx/Install/python2.7.10/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: broken data stream when reading image file

I am not familiar  with imageset IO implementation, hope someone could point out the reasons. 

Thanks, 
Xiuxia

**Comment by scttl** [comment]
Hi Xiuxia,

Can you let us know what OS, version you are running and also what version of libjpeg is installed?  You can determine the latter via `ldconfig -p | grep libjpeg`.  I'm wondering if you have an older version, and that is what is leading to the error your report.

**Comment by xiuxiazhang** [comment]
I am using Redhat 6.3 OS and installed jpeg-8c.

[zxx@ga85 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.3 (Santiago)

[zxx@ga85 ~]$ ldconfig -p | grep libjpeg
	libjpeg.so.62 (libc6,x86-64) => /usr/lib64/libjpeg.so.62
	
libjpeg.so.8 (libc6,x86-64) => /usr/local/lib/libjpeg.so.8
	libjpeg.so (libc6,x86-64) => /usr/local/lib/libjpeg.so
	libjpeg.so (libc6,x86-64) => /usr/lib64/libjpeg.so

**Comment by scttl** [comment]
Hi Xiuxia,

I do see you also have a 6.2 version, can you report what version of the lib is being used by PIL.  Instructions for doing this can be found here: http://stackoverflow.com/questions/24396727/find-which-libjpeg-is-being-used-by-pil-pillow

**Comment by xiuxiazhang** [comment]
Hi Scott,
      You're right. Although I installed libjpeg-8c, PIL is using libjpeg.so.62.  I adjusted the order of LD_LIBRARY_PATH. I uninstalled  pillow and reinstall pillow with --no-cache-dirs.  Finally PIL links to libjpeg.so.8.

Now the problem is fixed. Thank you.

**Comment by scttl** [comment]
Great to hear!
