### ISSUE TITLE
double and int ConvNets

### ISSUE THREAD

**Issue by ipanchenko** [NervanaSystems/neon#73]
Hello!
If I can use a convolution using double-precision floating point numbers?
I tried to use it modifying the examples but failed.

Don't you have a integer arithmetic convolutional layer?

**Comment by scttl** [comment]
Hi,

Yes double precision float networks should certainly be possible for some of the backends, were you thinking of GPU or CPU backend?  Were you looking to use float64 uniformly throughout all Tensors in all layers, or just for specific ones?

First you'll need to modify the YAML of each layer to set `backend_type: 'float64'` (this sets all tensors in that layer uniformly).  This should be all you need for fully connected layers, but for convolutional layers (on CPU backends at least) there's a small default dtype related issue that I've just pushed a fix for.

**Comment by ipanchenko** [comment]
Hello! I tried to make a float64 AlexNet modifying your examples for float16 and float32.
I'm interested in both GPU backends.
Here is my YAML: https://gist.github.com/ipanchenko/4e934e6c3f25fa319ec2
I get the same error on CPU and GPU.

*WARNING:neon.util.persist:deserializing object from:  examples/convnet/i1k-alexnet-fp64.yaml
Traceback (most recent call last):
  File "/opt/anaconda/bin/neon", line 235, in <module>
    experiment, result, status = main()
  File "/opt/anaconda/bin/neon", line 122, in main
    experiment = deserialize(args.yaml_file)
  File "/opt/anaconda/lib/python2.7/site-packages/neon/util/persist.py", line 192, in deserialize
    return yaml.safe_load(load_path)
  File "/opt/anaconda/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/opt/anaconda/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/opt/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/opt/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 43, in construct_document
    data = self.construct_object(node)
  File "/opt/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 90, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/opt/anaconda/lib/python2.7/site-packages/neon/util/persist.py", line 148, in obj_multi_constructor
    res = cls(**loader.construct_mapping(node, deep=True))
  File "/opt/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/opt/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/opt/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 90, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/opt/anaconda/lib/python2.7/site-packages/neon/util/persist.py", line 148, in obj_multi_constructor
    res = cls(**loader.construct_mapping(node, deep=True))
  File "/opt/anaconda/lib/python2.7/site-packages/neon/datasets/imageset.py", line 131, in __init__
    raise ValueError('Datatype not understood')
ValueError: Datatype not understood*

**Comment by scttl** [comment]
Sorry for closing earlier (was triggered from the commit I pushed)

**Comment by ipanchenko** [comment]
Thank you! But it seems like another problem with cudanet running should be closed to let me check it.
