### ISSUE TITLE
bug in the nervanagpu version of RecurrentLSTMLayer

### ISSUE THREAD

**Issue by mfassler** [NervanaSystems/neon#79]
These two commands:
```
neon examples/recurrent/mobydick-rnn-small.yaml
```
and:
```
neon -g nervanagpu examples/recurrent/mobydick-rnn-small.yaml
```
produce similar results.

But this command works:
```
neon examples/recurrent/mobydick-lstm-small.yaml
```
whereas this command does not:
```
neon -g nervanagpu examples/recurrent/mobydick-lstm-small.yaml
```

That last command produces the following error:
```
Traceback (most recent call last):
  File "/usr/bin/neon", line 235, in <module>
    experiment, result, status = main()
  File "/usr/bin/neon", line 203, in main
    result = experiment.run()
  File "/usr/lib/python2.7/site-packages/neon/experiments/fit_predict_err.py", line 99, in run
    super(FitPredictErrorExperiment, self).run()
  File "/usr/lib/python2.7/site-packages/neon/experiments/fit.py", line 106, in run
    self.model.fit(self.dataset)
  File "/usr/lib/python2.7/site-packages/neon/models/rnn.py", line 125, in fit
    self.fprop(debug=(True if (mb_id is -1) else False))
  File "/usr/lib/python2.7/site-packages/neon/models/rnn.py", line 225, in fprop
    self.rec_layer.fprop(y[tau-1], c[tau-1], inputs[tau], tau)
  File "/usr/lib/python2.7/site-packages/neon/layers/recurrent.py", line 513, in fprop
    self.cell_fprop(inputs, y, tau, 'i', self.gate_activation)
  File "/usr/lib/python2.7/site-packages/neon/layers/recurrent.py", line 453, in cell_fprop
    be.fprop_fc(self.temp_x[tau], xx, wx)
  File "/usr/lib/python2.7/site-packages/neon/backends/gpu.py", line 190, in fprop_fc
    self.ng.dot(weights, inputs, out)
  File "/usr/lib/python2.7/site-packages/nervanagpu/nervanagpu.py", line 969, in dot
    assert A.dtype.type == B.dtype.type == C.dtype.type
AssertionError
```
Some of the dtypes are float16, and some are float32.  This is because in `/usr/lib/python2.7/site-packages/neon/layers/recurrent.py` in `RecurrentLSTMLayer.allocate_output_bufs()` the dtype is being set to None, and so nervanagpu defaults to float16 (even though I set float32 as my default datatype).

If I change the code and force the dtype to float32, and re-run the command, I get the following output:
```
 ...

2015-09-02 17:20:29,173 INFO:val_init - Generating SparseEigenValGen values of shape (96, 64)
2015-09-02 17:20:29,174 INFO:val_init - matrix is non-square, no eigenvalue scaling.
2015-09-02 17:20:29,187 INFO:mobydick - sampling pct: 0.10
2015-09-02 17:20:29,193 INFO:mobydick - loading: pg2701
2015-09-02 17:20:29,771 WARNING:mobydick - Incompatible batch size. Discarding 288 samples...
2015-09-02 17:20:29,775 WARNING:mobydick - Incompatible batch size. Discarding 96 samples...
2015-09-02 17:20:29,806 WARNING:mobydick - Incompatible batch size. Discarding 288 samples...
2015-09-02 17:20:29,810 WARNING:mobydick - Incompatible batch size. Discarding 96 samples...
2015-09-02 17:20:29,856 INFO:rnn - commencing model fitting
2015-09-02 17:20:40,041 INFO:rnn - epoch: 1, total training error: nan
2015-09-02 17:20:49,183 INFO:rnn - epoch: 2, total training error: nan
2015-09-02 17:20:58,322 INFO:rnn - epoch: 3, total training error: nan
2015-09-02 17:21:07,434 INFO:rnn - epoch: 4, total training error: nan

 ...

```
All of the mnist models seem to work correctly with the nervanagpu backend.  A MLP that we are using in-house seems to work correctly with the nervanagpu backend.  (I haven't tested much else.)

**Comment by ursk** [comment]
Hi Mark,
thanks for pointing out the issue. This appears to be a bug with the current neon 0.9.0 release. As a quick workaround I would suggest that you use v0.8.2, where the example works with both the CPU and NervanaGPU backend. (Note that changing the default_dtype = np.float16 to float32 in nervanagpu.py will still be required). 

For a more permanent solution, we will soon release a new version of neon with extensive improvements to RNNs and LSTMs.

**Comment by mfassler** [comment]
Hello,
Thank you for the confirmation.  

I can confirm that commit 5d28ddfc512afbfb3... works
and commit 19829290a7...  does not.  
(in both cases I am forcing the dtype to float32)
